Add ECM variables
pybamm-team/PyBaMM pull request #1204
Opened 2020-10-21 12:44 UTC by TomTranter

# Description

Some extra variables for the ecm model based on using pybamm in an external equivalent circuit model

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/master/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2020-10-21 13:58 UTC, rtimms requested changes
looks good thanks, would you be able to reorganize this a little so that all the ECM variables are defined together and just add a short comment explaining them (its not obvious as we have no other ECM stuff in pybamm)

2020-10-22 15:03 UTC, rtimms approved these changes

2020-10-22 16:01 UTC, TomTranter commented
@rtimms why failing on mac? I'm not authorized to merge this so please do so if you're ready. Thanks

2020-10-22 16:46 UTC, tinosulzer commented
Everything is failing on mac right now. We need to wait for github to fix it

2020-10-23 15:36 UTC, merged