Fix load function
pybamm-team/PyBaMM pull request #1676
Opened 2021-09-15 19:39 UTC by brosaplanella

# Description

Fix the `load_function` bug on main branch.

Fixes #1673 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

2021-09-15 20:20 UTC, tinosulzer approved these changes

2021-09-15 20:20 UTC, tinosulzer requested changes
Need to also manually increment version numbers

2021-09-15 20:51 UTC, tinosulzer approved these changes

2021-09-16 00:49 UTC, priyanshuone6 commented
@brosaplanella could you also include changes from [this PR](https://github.com/pybamm-team/PyBaMM/pull/1672) to this release

2021-09-16 08:50 UTC, priyanshuone6 approved these changes
Thanks @brosaplanella

2021-09-16 09:47 UTC, merged