Rename tortuosity to transport efficiency
pybamm-team/PyBaMM pull request #1950
Opened 2022-02-25 18:30 UTC by Vaibhav-Chopra-GT

# Description

Renamed tortuosity to transport_efficiency in the entire code. Could you please let me know if I should add _ in dictionary keys?

Fixes # (issue)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2022-02-26 09:58 UTC, Saransh-cpp reviewed
The tests (running `pybamm.print_citations()` in the notebooks on `Ubuntu` with `Python 3.8`) are most probably failing due to a different reason, given that the corresponding tests running with different `Python` versions are passing.

`IPython` had a [new release](https://pypi.org/project/ipython/) on 25th February, which is probably responsible for this. Should we pin the `IPython` version?

2022-02-26 10:02 UTC, Saransh-cpp commented
Oh, the new release has an issue - https://github.com/ipython/ipython/issues/13554 - which should be fixed soon. No need to pin the version.

2022-03-08 16:09 UTC, tinosulzer requested changes
Thanks @Vaibhav-Chopra-GT , only change is there shouldn't be an underscore in any of the strings

2022-03-08 16:09 UTC, tinosulzer commented on pybamm/input/parameters/lithium_ion/negative_electrodes/graphite_UMBL_Mohtat2020/parameters.csv
> +Negative electrode transport_efficiency, 0.16,
there shouldn't be an underscore here (and in other CSVs)

2022-03-08 16:09 UTC, tinosulzer commented on pybamm/models/full_battery_models/lead_acid/loqs.py
> +            "leading-order electrolyte transport_efficiency"
no underscore

2022-03-08 16:09 UTC, tinosulzer commented on pybamm/models/submodels/electrode/ohm/base_ohm.py
> +                * variables["Positive electrode transport_efficiency"]
no underscore

2022-03-13 10:39 UTC, Vaibhav-Chopra-GT commented
@tinosulzer removed underscore in strings and CSVs

2022-03-13 13:57 UTC, tinosulzer approved these changes

2022-03-13 13:57 UTC, tinosulzer commented
Thanks!

2022-03-13 13:57 UTC, merged

2022-03-14 04:02 UTC, priyanshuone6 commented
@all-contributors please add @Vaibhav-Chopra-GT for code