remove external_variables
pybamm-team/PyBaMM pull request #2502
Opened 2022-11-29 14:05 UTC by TomTranter

# Description

Remove external_variables which have functionality that is now completely replicable with input parameters. Motivation is to simplify code and reduce redundant functionality. Also relates to a liionpack issue with handling the two types of data seperately and is cleaner to use inputs.

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2022-12-06 14:20 UTC, tinosulzer requested changes
Existing changes look good but there are more lines to remove, see coverage

2022-12-06 14:20 UTC, tinosulzer commented on tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_external/test_external_current_collector.py
> +    pass
delete this test

2022-12-06 14:20 UTC, tinosulzer commented on tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_external/test_external_temperature.py
> +    # def test_external_temperature(self):
delete these

2022-12-06 14:20 UTC, tinosulzer commented on tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_spme.py
> +    # def test_external_variables(self):
delete

2022-12-13 12:28 UTC, TomTranter commented
@tinosulzer tests passing but some benchmarks are failing. How can I run just the failing ones locally easily?

2022-12-13 15:56 UTC, tinosulzer approved these changes
Thanks @TomTranter

2022-12-13 18:06 UTC, merged