Remove brew-sundials from the recommended developer installations
pybamm-team/PyBaMM pull request #2925
Opened 2023-05-04 09:13 UTC by jsbrittain

# Description

The (Mac recommended) `brew` install procedure for sundials does not link the cmake args that are required by `tox -e dev`. Here, we simplify the developer installation procedure for Mac, bringing it in-line with that for linux, by using `tox -e pybamm-requires` to download, compile and install the SuiteSparse and SUNDIALS libraries.

Fixes #2897 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [X] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

_(documentation change only)_
~~[ ] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)~~
~~[ ] All tests pass: `$ python run-tests.py --all`~~
- [X] The documentation builds: `$ python run-tests.py --doctest`

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2023-05-04 11:05 UTC, agriyakhetarpal commented
For Linux installation, and in addition to `tox -e pybamm-requires` – maybe the `pybamm_install_odes` command can be updated to also install OpenBLAS and not just SUNDIALS in a PR in the future? 

This can remove the need for the note about the error `A library with BLAS API not found. Please specify library location.
   -- LAPACK requires BLAS` which is mentioned in the Troubleshooting section of the GNU/Linux installation section documentation at `GNU-linux.rst`

2023-05-05 09:50 UTC, brosaplanella approved these changes
Looks good to me, but I don't use Mac, so I have requested a review from Valentin who uses it

2023-05-05 22:06 UTC, tinosulzer requested changes
Looks good except changelog needs updating

2023-05-05 22:06 UTC, tinosulzer commented on CHANGELOG.md
> +- Remove brew install for Mac from the recommended developer installation options for SUNDIALS ([#2925](https://github.com/pybamm-team/PyBaMM/pull/2925))
this needs to be moved to the new section

2023-05-08 18:58 UTC, tinosulzer approved these changes

2023-05-08 20:39 UTC, merged