Add self-hosted actions to periodic tests
pybamm-team/PyBaMM pull request #2929
Opened 2023-05-05 16:10 UTC by BradyPlanden

# Description

This updates the `run_periodic_tests.yml` workflow to include the self-hosted m-series runner.

Fixes #2884 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all`
- [x] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2023-06-27 15:08 UTC, Saransh-cpp reviewed
Merging the nox PR generated conflicts with a lot of open PRs 😬

2023-06-27 15:08 UTC, Saransh-cpp commented on .github/workflows/run_periodic_tests.yml
> +            python -m tox -e mac-windows-unit
```suggestion
            python -m pip install --upgrade pip wheel setuptools nox
            nox -s unit
```

2023-06-27 15:08 UTC, Saransh-cpp commented on .github/workflows/run_periodic_tests.yml
> +            python -m tox -e mac-windows-integration
```suggestion
            nox -s integration
```

2023-06-30 14:25 UTC, martinjrobins requested changes
looks great, thanks @BradyPlanden, couple of suggestions below, and add @Saransh-cpp's changes as well

2023-06-30 14:25 UTC, martinjrobins commented on .github/workflows/run_periodic_tests.yml
> +            export PATH="$PYENV_ROOT/bin:$PATH"
should put PATH in `env` (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv)

2023-06-30 14:25 UTC, martinjrobins commented on .github/workflows/run_periodic_tests.yml
> +            export PATH="$PYENV_ROOT/bin:$PATH"
same here

2023-07-03 12:49 UTC, BradyPlanden commented
Thanks @martinjrobins and @Saransh-cpp, this is updated now and should be good for another review :+1:

2023-07-10 15:20 UTC, martinjrobins approved these changes
Thanks @BradyPlanden , happy to merge this now :)

2023-07-10 15:34 UTC, merged