Make `nox -s dev` run like `nox -s dev --verbose`
pybamm-team/PyBaMM pull request #3104
Opened 2023-07-04 20:32 UTC by arjxn-py

# Description

Make nox -s dev run like nox -s dev --verbose to so that all commands run is shown.

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all`
- [ ] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2023-07-04 20:50 UTC, agriyakhetarpal commented
The --verbose flag allows developers to see what packages are installed by `pip` in the environments, which is especially useful for the `unit`, `examples`, and the `docs` environments. Is there a way to increase the verbosity for all `nox` environments by default?

2023-07-04 20:58 UTC, arjxn-py commented
> The --verbose flag allows developers to see what packages are installed by `pip` in the environments, which is especially useful for the `unit`, `examples`, and the `docs` environments. Is there a way to increase the verbosity for all `nox` environments by default?

There doesn't seem to be having much info available about increasing the verbosity level by default atm. 

I could find this much according to the docs : 
>> ## Controlling commands verbosity
>> By default, Nox will only show output of commands that fail, or, when the commands get passed silent=False. By passing --verbose to Nox, all output of all commands run is shown, regardless of the silent argument.

2023-07-04 21:51 UTC, arjxn-py commented
Apparantly I tried doing this & some other things as well
```Python 
nox.options.verbose = True
```
But it did't make any effect on verbosity.

2023-07-05 19:55 UTC, agriyakhetarpal requested changes

2023-07-05 19:55 UTC, agriyakhetarpal commented on docs/source/user_guide/installation/install-from-source.rst
> +**Note** : It is recommended to use ``--verbose`` or ``-v`` to see outputs of all commands run.
```suggestion
.. note::
    It is recommended to use ``--verbose`` or ``-v`` to see outputs of all commands run.
```

2023-07-05 19:55 UTC, agriyakhetarpal commented on docs/source/user_guide/installation/install-from-source.rst
> +**Note** : It is recommended to use ``--verbose`` or ``-v`` to see outputs of all commands run.
Just some better formatting

2023-07-05 19:57 UTC, arjxn-py commented on docs/source/user_guide/installation/install-from-source.rst
> +**Note** : It is recommended to use ``--verbose`` or ``-v`` to see outputs of all commands run.
Thanks @agriyakhetarpal

2023-07-05 21:35 UTC, Saransh-cpp approved these changes
Looks great, thanks @arjxn-py!

2023-07-05 21:40 UTC, agriyakhetarpal approved these changes
I checked the other command-line arguments if we can add any more, I think we should also document the `--install-only` command since it allows the creation of an environment but only installs the dependencies, to keep it ready for later use—this could be useful for the `unit` and `docs` environments

2023-07-05 21:43 UTC, arjxn-py commented
> I checked the other command-line arguments if we can add any more, I think we should also document the `--install-only` command since it allows the creation of an environment but only installs the dependencies, to keep it ready for later use—this could be useful for the `unit` and `docs` environments

Yes, I had added it [here](https://github.com/pybamm-team/PyBaMM/pull/3104/files#diff-ceedebcbf80d97f94255635c9cf4d2b5105c89a1e099f1e090127ae35d3f08b2R241)

2023-07-05 21:43 UTC, merged