Add `max_step` arg in `basesolver`
pybamm-team/PyBaMM pull request #3106
Opened 2023-07-04 22:54 UTC by arjxn-py

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2253 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all`
- [ ] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-02-15 14:12 UTC, arjxn-py commented
Yes, i'll try to finish this up asap.
Apologies as this one went down in the stack, thanks for pinging.

2024-02-19 09:41 UTC, agriyakhetarpal commented
It looks like Chocolatey community repositories are under maintenance, which explains the Windows job failures.

2024-02-21 06:51 UTC, arjxn-py commented
Should also do changelog for this, right?

2024-02-21 11:13 UTC, arjxn-py commented on .github/workflows/work_precision_sets.yml
> +          python benchmarks/work_precision_sets/time_vs_dt_event.py
This file also needs to be renamed.

2024-02-21 11:17 UTC, arjxn-py commented on .github/workflows/work_precision_sets.yml
> +          python benchmarks/work_precision_sets/time_vs_dt_event.py
Done in [`68c2925`](https://github.com/pybamm-team/PyBaMM/pull/3106/commits/68c29256797fd20fdef007f54264a1a48925d493)

2024-04-08 10:18 UTC, arjxn-py commented
@rtimms I'd be happy to have your review & input on this. Thanks.

2024-04-09 17:13 UTC, rtimms requested changes
In all of the solver classes you need to pass `max_step` to the actual call to solve in the appropriate way inside the `_integrate` method. Right now passing `max_step` doesn't do anything. E.g. in `ScipySolver` you need to pass `max_step` as a keyword argument to `solve_ivp`

2024-04-09 17:13 UTC, rtimms commented on pybamm/solvers/algebraic_solver.py
> +    max_step : float, optional
the algebraic solver doesn't step in time so it doesn't make sense for it to be an argument here

2024-04-09 17:13 UTC, rtimms commented on pybamm/solvers/casadi_algebraic_solver.py
>  class CasadiAlgebraicSolver(pybamm.BaseSolver):
as above

2024-04-09 17:13 UTC, rtimms commented on pybamm/solvers/base_solver.py
> +def validate_max_step(max_step):
we don't validate other arguments such as tolerances. my guess is that all the solvers will have their own check to make sure max step makes sense, so maybe we should remove this?

2024-04-09 17:13 UTC, rtimms commented on pybamm/solvers/casadi_solver.py
> +    dt_event : float, optional
I agree `dt_event` is a better name for this. Can you make it so that the solver also still accepts `dt_max` and raises a `DeprecationWarning`?

2024-12-13 17:10 UTC, agriyakhetarpal commented
Closing since this is superseded by #4673.

2024-12-13 17:10 UTC, closed without merging