Add more precommits
pybamm-team/PyBaMM pull request #3192
Opened 2023-07-26 16:33 UTC by arjxn-py

# Description

Suggested in [#3180(comment)](https://github.com/pybamm-team/PyBaMM/pull/3180#issuecomment-1646698735) & [#3180(comment)](https://github.com/pybamm-team/PyBaMM/pull/3180#issuecomment-1648059280), this PR aims to add some more default pre-commit hooks.

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all`
- [ ] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2023-07-26 17:11 UTC, Saransh-cpp reviewed
@arjxn-py your branch is behind develop; hence, the failure. You'll have to merge develop. Also, feel free to add other pygrep hooks and disallow-caps in this PR itself.

2023-07-26 17:31 UTC, arjxn-py commented
Ahh thanks @Saransh-cpp I was wondering why it wasn't giving conflicts on PR itself but in pre-commit CI, cool it was just a sync thing 🙂

2023-07-26 17:34 UTC, arjxn-py commented
Now I wonder it it require some special permission here in CI to fix files inside `.github/workflow/...` because It is fixing them locally

2023-07-26 20:43 UTC, Saransh-cpp commented
> GitHub prevented pre-commit.ci from autofixing this pr due to autofixes to a workflow file

You'll have to run pre-commit locally 🙂

2023-07-29 16:31 UTC, Saransh-cpp requested changes
Thanks, @arjxn-py! You'll have to rewrite the git history. I see that there are multiple commits with pre-commit changes, but there should be only 1, with its hash written down in the git-revs file.

2023-07-29 16:31 UTC, Saransh-cpp commented on .pre-commit-config.yaml
> +          exclude: ^docs ^.github/workflows
Why exclude workflows and docs?

2023-07-29 16:31 UTC, Saransh-cpp commented on README.md
> +[![pre-commit](https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit)](https://github.com/pre-commit/pre-commit)
This is maybe not required 🙂

2023-08-02 07:43 UTC, arjxn-py commented on .pre-commit-config.yaml
> +          exclude: ^docs ^.github/workflows
Not excluding now.

2023-08-02 15:31 UTC, Saransh-cpp reviewed
Thanks, @arjxn-py! Looks great! You'll still need to figure out how to fix the git history, for example, there are `pre-commit` changes in https://github.com/pybamm-team/PyBaMM/pull/3192/commits/13964f91b366165d21ef529e40a13159f1da0e6c and https://github.com/pybamm-team/PyBaMM/pull/3192/commits/96fc3872c8dc2688e24705e87caccea5fe7abd64, and they should not be there in these commits.

2023-08-04 16:11 UTC, Saransh-cpp approved these changes

2023-08-04 20:25 UTC, merged