feat: adding towncrier
pybamm-team/PyBaMM pull request #3278
Opened 2023-08-20 05:13 UTC by arunavabasu-03

# Description
### Fixes #2885
Using towncrier for CHANGELOG.md 

## Type of change

Using towncrier for CHANGELOG.md

2023-08-20 05:15 UTC, arunavabasu-03 commented
@tinosulzer pls check do you want this way or their is any approach i have to follow , just done for v23.5 , if it is ok then i goona add all the versions !!

2023-08-20 19:08 UTC, Saransh-cpp requested changes
Thanks for working on this, @arunavabasu-03! 🙂 

Took a quick look, and will deep dive into `towncrier` in a few days!

2023-08-20 19:08 UTC, Saransh-cpp commented on changelogs/v23.5/bugfix.rst
> +- Fix `pybamm_install_odes` and update the required SUNDIALS version ([#2958](https://github.com/pybamm-team/PyBaMM/pull/2958))
[Links are handled differently](https://docutils.sourceforge.io/docs/user/rst/quickref.html#hyperlink-targets) in `rst`, which is why `pre-commit` is failing.

2023-08-20 19:11 UTC, Saransh-cpp requested changes

2023-08-20 19:11 UTC, Saransh-cpp commented on changelogs/v23.5/breakingchanges.rst
> +=========
```suggestion
Breaking changes
================
```

2023-08-20 19:11 UTC, Saransh-cpp commented on changelogs/v23.5/bugfix.rst
> +- Fix `pybamm_install_odes` and update the required SUNDIALS version ([#2958](https://github.com/pybamm-team/PyBaMM/pull/2958))
`rst` uses double backticks
```suggestion
- Fix ``pybamm_install_odes`` and update the required SUNDIALS version ([#2958](https://github.com/pybamm-team/PyBaMM/pull/2958))
```

2023-08-20 19:11 UTC, Saransh-cpp commented on changelogs/v23.5/bugfix.rst
> +- Fix `bpx.py` to correctly generate parameters for "lumped" thermal model ([#2860](https://github.com/pybamm-team/PyBaMM/issues/2860))
```suggestion
- Fix ``bpx.py`` to correctly generate parameters for "lumped" thermal model ([#2860](https://github.com/pybamm-team/PyBaMM/issues/2860))
```

2023-08-20 19:11 UTC, Saransh-cpp commented on changelogs/v23.5/feature.rst
> +- If a solution contains cycles and steps, the cycle number and step number are now saved when `solution.save_data()` is called ([#2931](https://github.com/pybamm-team/PyBaMM/pull/2931))
```suggestion
- If a solution contains cycles and steps, the cycle number and step number are now saved when ``solution.save_data()`` is called ([#2931](https://github.com/pybamm-team/PyBaMM/pull/2931))
```

2023-08-20 19:11 UTC, Saransh-cpp commented on changelogs/v23.5/feature.rst
> +- Experiments can now be given a `start_time` to define when each step should be triggered ([#2616](https://github.com/pybamm-team/PyBaMM/pull/2616))
```suggestion
- Experiments can now be given a ``start_time`` to define when each step should be triggered ([#2616](https://github.com/pybamm-team/PyBaMM/pull/2616))
```

2023-08-20 19:11 UTC, Saransh-cpp commented on changelogs/v23.5/optimizations.rst
> +=========
```suggestion
Optimizations
=============
```

2023-08-20 19:11 UTC, Saransh-cpp commented on changelogs/v23.5/optimizations.rst
> +- Removed `importlib_metadata` as a required dependency for user installations ([#3050](https://github.com/pybamm-team/PyBaMM/pull/3050))
```suggestion
- Test ``JaxSolver``'s compatibility with Python ``3.8``, ``3.9``, ``3.10``, and ``3.11`` ([#2958](https://github.com/pybamm-team/PyBaMM/pull/2958))
- Update Jax (0.4.8) and JaxLib (0.4.7) compatibility ([#2927](https://github.com/pybamm-team/PyBaMM/pull/2927))
- Migrate from ``tox=3.28`` to ``nox`` ([#3005](https://github.com/pybamm-team/PyBaMM/pull/3005))
- Removed ``importlib_metadata`` as a required dependency for user installations ([#3050](https://github.com/pybamm-team/PyBaMM/pull/3050))
```

2023-08-20 19:11 UTC, Saransh-cpp commented on changelogs/v23.5/bugfix.rst
> +- Fix `pybamm_install_odes` and update the required SUNDIALS version ([#2958](https://github.com/pybamm-team/PyBaMM/pull/2958))
```suggestion
- Fix ``pybamm_install_odes`` and update the required SUNDIALS version ([#2958](https://github.com/pybamm-team/PyBaMM/pull/2958))
```

2023-08-20 19:32 UTC, agriyakhetarpal commented
I think we can convert the entire `CHANGELOG.md` file using [executablebooks/rst-to-myst](https://rst-to-myst.readthedocs.io/en/stable/index.html), or we could just [keep it in Markdown](https://towncrier.readthedocs.io/en/stable/markdown.html) like it is already because I feel the syntax is more intuitive

2023-10-08 15:47 UTC, closed without merging

2023-10-08 16:36 UTC, agriyakhetarpal commented
@arunavabasu-03, was this in error or would you not be working on this feature anymore?