Documentation suggestions for the installation and tutorials
pybamm-team/PyBaMM pull request #3318
Opened 2023-09-10 19:58 UTC by kratman

# Description

Minor updates to the documentation pages.

Changes:
 - Fixes a broken link between the windows installation page and the windows WSL installation page. The broken link was caused by having the incorrect name for the windows WSL page.
 - Removes a note about using chocolatey from the MacOS install from source tab. I left the note in the Linux install from source tab for the use-case where a windows installation is done with Cygwin. I can remove the note from both MacOS and Linux if desired.
 - Tutorial 6 now uses a temporary folder to write the pickle files. I feel it is cleaner to write output to a specific folder rather than the current working directory. Since this is my opinion and it does add a small amount of complexity, I can remove this change if it is unwanted.

## Type of change

Documentation and notebook changes only. No additional features or updates to the library.

To-do:
- [ ] Update change log with PR number and description.

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

2023-09-12 17:02 UTC, Saransh-cpp requested changes
Thanks for working on this, @kratman! Looks good overall.

> Tutorial 6 now uses a temporary folder to write the pickle files. I feel it is cleaner to write output to a specific folder rather than the current working directory

I think this should be reverted, given that the change makes it difficult for new Python/PyBaMM users to follow up with the tutorial. Experienced users will not face any difficulties, but this might push away newcomers.

2023-09-12 17:07 UTC, kratman commented
No problem. I will revert that change in an hour or so. Thanks for taking a look.

2023-09-13 15:06 UTC, Saransh-cpp approved these changes

2023-09-13 15:08 UTC, Saransh-cpp commented
@all-contributors please add @kratman for docs and infra

2023-09-13 15:50 UTC, merged