Using `f-string` for string formatting
pybamm-team/PyBaMM pull request #3551
Opened 2023-11-22 20:13 UTC by prady0t

# Description

Replaced `format()` with `fstring` wherever possible.

Fixes #3496 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2023-11-25 08:34 UTC, prady0t commented
Please have a look!

2023-11-25 21:06 UTC, agriyakhetarpal reviewed
Thanks, @prady0t! I have gone through all the changes and most of them look good to me, except the ones where [special characters](https://docs.python.org/3/library/string.html#format-string-syntax) are used such as `{!s}` (see the [failing unit tests](https://github.com/pybamm-team/PyBaMM/actions/runs/6988039521)). We should fix the tests wherever it is possible to do so, and in cases where it isn't, keep using `.format()`.

2023-11-27 04:06 UTC, kratman requested changes
Reviewed all but the notebooks.

Don't take the number of comments and suggestions here personally. Most of what I suggested was cleanup of strings that existed before you started.

Also please double check my suggestions before merging them. I did this review very late.

2023-11-27 04:06 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
>                  )
```suggestion
                "User-suppled edges has should have length (npts + 1) but has length "
                f"{len(edges)}.Number of points (npts) for domain {spatial_var.domain} is {npts}.".replace(
                    "\n                ", " "
                )
```

2023-11-27 04:06 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
> +                 for domain {spatial_var.domain}."""
```suggestion
                f"First entry of edges is {edges[0]}, but should be equal to {spatial_lims["min"]} "
                "for domain {spatial_var.domain}."
```

2023-11-27 04:06 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
> +                for domain {spatial_var.domain}."""
```suggestion
                f"Last entry of edges is {edges[-1]}, but should be equal to {spatial_lims["max"]} "
                "for domain {spatial_var.domain}."
```

2023-11-27 04:06 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
> +                 for domain {spatial_var.dom}."""
```suggestion
                f"First entry of edges is {edges[0]}, but should be equal to {spatial_lims["min"]} "
                "for domain {spatial_var.dom}."
```

2023-11-27 04:06 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
> +                for domain {spatial_var.domain}."""
```suggestion
                f"Last entry of edges is {edges[-1]}, but should be equal to {spatial_lims["max"]} "
                "for domain {spatial_var.domain}."
```

2023-11-27 04:06 UTC, kratman commented on pybamm/meshes/scikit_fem_submeshes.py
> +                but have coordinate systems {spatial_vars[0].coord_sys} and {spatial_vars[1].coord_sys}"""
```suggestion
                f"spatial variables should have the same coordinate system, "
                "but have coordinate systems {spatial_vars[0].coord_sys} and {spatial_vars[1].coord_sys}"
```

2023-11-27 04:06 UTC, kratman commented on pybamm/meshes/scikit_fem_submeshes.py
> +                     domain {var.domain} is {npts[var.name]}."""
```suggestion
                    f"User-suppled edges has should have length npts but has length {len(edges[var.name])}. "
                    "Number of points (npts) for variable {var.name} in "
                    "domain {var.domain} is {npts[var.name]}."
```

2023-11-27 04:06 UTC, kratman commented on pybamm/meshes/scikit_fem_submeshes.py
> +                     for variable {var.name} in domain {var.domain}."""
```suggestion
                    f"First entry of edges is {edges[var.name][0]}, but should be equal to {lims[var.name]["min"]} "
                    "for variable {var.name} in domain {var.domain}."
```

2023-11-27 06:24 UTC, prady0t commented
Thanks for all the suggestions @agriyakhetarpal @kratman . Will do the requested changes asap.

2023-11-27 21:27 UTC, prady0t commented
How to resolve conflicts? `Resolve conflicts` button is grayed out.

2023-11-27 23:36 UTC, prady0t commented on pybamm/expression_tree/operations/evaluate_python.py
> +
Please have a look here @kratman

2023-11-27 23:53 UTC, kratman reviewed
I am really sorry, I think these were my mistakes when I reviewed yesterday.

2023-11-27 23:53 UTC, kratman commented on pybamm/discretisations/discretisation.py
> +                "'current collector', but {symbol} has domain {domain}"
```suggestion
                f"'current collector', but {symbol} has domain {domain}"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/expression_tree/averages.py
> +            "but symbol has domains {symbol.domain}"
```suggestion
            f"but symbol has domains {symbol.domain}"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/expression_tree/averages.py
> +            "but symbol has domains {symbol.domain}"
```suggestion
            f"but symbol has domains {symbol.domain}"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/expression_tree/binary_operators.py
> +            "but symbols have domains {left.domain} and {right.domain}"
```suggestion
            f"but symbols have domains {left.domain} and {right.domain}"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/expression_tree/symbol.py
> +            "for symbol {self} of type {type(self)}"
```suggestion
            f"for symbol {self} of type {type(self)}"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/expression_tree/unary_operators.py
> +                    "'current collector', but {child} has domain {child.domain[0]}"
```suggestion
                    f"'current collector', but {child} has domain {child.domain[0]}"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/expression_tree/unary_operators.py
>                  + "evaluate on nodes."
```suggestion
                f"Cannot upwind '{child}' since it does not "
                "evaluate on nodes."
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
> +                "for domain {spatial_var.domain}."
```suggestion
                f"for domain {spatial_var.domain}."
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
> +                "for domain {spatial_var.domain}."
```suggestion
                f"for domain {spatial_var.domain}."
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
> +                "for domain {spatial_var.dom}."
```suggestion
                f"for domain {spatial_var.dom}."
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/one_dimensional_submeshes.py
> +                "for domain {spatial_var.domain}."
```suggestion
                f"for domain {spatial_var.domain}."
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/scikit_fem_submeshes.py
> +                "but have coordinate systems {spatial_vars[0].coord_sys} and {spatial_vars[1].coord_sys}"
```suggestion
                f"but have coordinate systems {spatial_vars[0].coord_sys} and {spatial_vars[1].coord_sys}"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/scikit_fem_submeshes.py
> +                    "Number of points (npts) for variable {var.name} in "
```suggestion
                    f"Number of points (npts) for variable {var.name} in "
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/scikit_fem_submeshes.py
> +                    "domain {var.domain} is {npts[var.name]}."
```suggestion
                    f"domain {var.domain} is {npts[var.name]}."
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/scikit_fem_submeshes.py
> +                    "for variable {var.name} in domain {var.domain}."
```suggestion
                    f"for variable {var.name} in domain {var.domain}."
```

2023-11-27 23:53 UTC, kratman commented on pybamm/meshes/scikit_fem_submeshes.py
> +                    "for variable {var.name} in domain {var.domain}."
```suggestion
                    f"for variable {var.name} in domain {var.domain}."
```

2023-11-27 23:53 UTC, kratman commented on pybamm/models/base_model.py
>                                  + "Check the selected "
```suggestion
                                f"Missing variable for submodel '{submodel_name}': {key}.\n"
                                "Check the selected "
```

2023-11-27 23:53 UTC, kratman commented on pybamm/models/full_battery_models/base_battery_model.py
> +                "Setting boundary conditions for {submodel_name} submodel ({self.name})"
```suggestion
                f"Setting boundary conditions for {submodel_name} submodel ({self.name})"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/models/full_battery_models/base_battery_model.py
> +                "Setting initial conditions for {submodel_name} submodel ({self.name})"
```suggestion
                f"Setting initial conditions for {submodel_name} submodel ({self.name})"
```

2023-11-27 23:53 UTC, kratman commented on pybamm/solvers/jax_solver.py
> +            raise ValueError("method must be one of {method_options}")
```suggestion
            raise ValueError(f"method must be one of {method_options}")
```

2023-11-28 06:48 UTC, prady0t commented
Commited   all   the suggested changes

2023-11-28 09:12 UTC, Saransh-cpp requested changes
Thanks for taking this up, @prady0t! Given that we now have ruff's config in `pyproject.toml`, I will suggest you to -
1. reset all the commits in your branch
    ```
    git remote add upstream https://github.com/pybamm-team/PyBaMM  # will add a remote pointing to the original pybamm repo
    git fetch --all  # fetch everything from all the remotes
    git reset --hard upstream/develop  # match your format-fix branch with pybamm's develop (hard reset - all changes lost)
    ```
2. Uncomment the following line to activate pyupgrade related rules in ruff. This will automatically update all the non-f-string occurrences along with a few other good code upgrades.
https://github.com/pybamm-team/PyBaMM/blob/c86f8fe676d40b77279aab26a01049266627b49c/pyproject.toml#L199
3. Commit this change without invoking pre-commit -
    ```
    git add pyproject.toml
    git commit -m "Your message" --no-verify
    ```
4. Invoke pre-commit
    ```
    pre-commit run -a
    ```
5. Make any manual fixes if required
6. Add and commit the changes
7. Add the commit hash to https://github.com/pybamm-team/PyBaMM/blob/develop/.git-blame-ignore-revs. We are doing this to preserve [`git blame`](https://git-scm.com/docs/git-blame). We don't want the git blame to be polluted with pre-commit changes.
8. Create another commit and force push
    ```
    git push -f
    ```

---

Please let us know if you need any help along the way!

2023-11-28 21:46 UTC, prady0t commented
> Thanks for taking this up, @prady0t! Given that we now have ruff's config in `pyproject.toml`, I will suggest you to -
> 
> 1. reset all the commits in your branch
>    ```
>    git remote add upstream https://github.com/pybamm-team/PyBaMM  # will add a remote pointing to the original pybamm repo
>    git fetch --all  # fetch everything from all the remotes
>    git reset --hard upstream/develop  # match your format-fix branch with pybamm's develop (hard reset - all changes lost)
>    ```
> 2. Uncomment the following line to activate pyupgrade related rules in ruff. This will automatically update all the non-f-string occurrences along with a few other good code upgrades.
>    https://github.com/pybamm-team/PyBaMM/blob/c86f8fe676d40b77279aab26a01049266627b49c/pyproject.toml#L199
> 3. Commit this change without invoking pre-commit -
>    ```
>    git add pyproject.toml
>    git commit -m "Your message" --no-verify
>    ```
> 4. Invoke pre-commit
>    ```
>    pre-commit run -a
>    ```
> 5. Make any manual fixes if required
> 6. Add and commit the changes
> 7. Add the commit hash to https://github.com/pybamm-team/PyBaMM/blob/develop/.git-blame-ignore-revs. We are doing this to preserve [`git blame`](https://git-scm.com/docs/git-blame). We don't want the git blame to be polluted with pre-commit changes.
> 8. Create another commit and force push
>    ```
>    git push -f
>    ```
> 
> Please let us know if you need any help along the way!

Im not sure how `ruff` works and what `pyupgrade` does (as per documentation it automatically upgrades syntax to newer version) but if it achieves desired changes just by changing one line should I not make a new branch from main and do the above changes to `pyproject.toml` there? If it achives similar changes I can make a new PR from that branch, if it doesn't we can stick to this PR then? I'm a bit concerned as this issue deals with large number of lines scattered over multiple files, changing them manually is a piece of work. Although it's just a newbie's advice. I can totally go with yours if this doesn't make much sense.

2023-11-30 21:12 UTC, prady0t commented
I've opened a new PR. It has higher number of line changes than this and plus not all changes are `f-string` related. Please review.

2023-11-30 21:21 UTC, kratman commented
Ok go ahead and close this one. I will review the other one

2023-11-30 21:25 UTC, closed without merging