Using pyupgrade to convert string formatting to `f-string`.
pybamm-team/PyBaMM pull request #3579
Opened 2023-11-30 21:05 UTC by prady0t

Fixes #3496 

Linked to PR #3551

2023-12-01 10:32 UTC, Saransh-cpp requested changes
Thanks for working on this, @prady0t!

1. Not all pre-commit related changes were included in https://github.com/pybamm-team/PyBaMM/pull/3579/commits/41019cf34259c2c218f48d847eef75d261759c37, so you might have to reset the commits and include all the changes in a single commit.
2. Some pre-commit suggestions must be resolved manually. These are visible here - https://results.pre-commit.ci/run/github/155538761/1701378735.92sVUq40SsSDBx8YpLEX4w. You can access this by scrolling to the bottom of your PR and clicking "details" on the pre-commit.ci job.
3. There are a few typing fixes required for the pre-commit job to pass. Adding `UP007` to the list of excluded checks in `pyproject.toml` with a small note should fix this for now. (@pipliggins could fix these and add the check back in #3578.)

2023-12-01 22:36 UTC, prady0t commented
> Thanks for working on this, @prady0t!
> 
> 1. Not all pre-commit related changes were included in [41019cf](https://github.com/pybamm-team/PyBaMM/commit/41019cf34259c2c218f48d847eef75d261759c37), so you might have to reset the commits and include all the changes in a single commit.
> 2. Some pre-commit suggestions must be resolved manually. These are visible here - https://results.pre-commit.ci/run/github/155538761/1701378735.92sVUq40SsSDBx8YpLEX4w. You can access this by scrolling to the bottom of your PR and clicking "details" on the pre-commit.ci job.
> 3. There are a few typing fixes required for the pre-commit job to pass. Adding `UP007` to the list of excluded checks in `pyproject.toml` with a small note should fix this for now. (@pipliggins could fix these and add the check back in [Adds typing to expression tree #3578](https://github.com/pybamm-team/PyBaMM/pull/3578).)

Am I supposed to add `UP007` here? https://github.com/pybamm-team/PyBaMM/blob/ebacf496a4322b084b7c4058599755b45008283b/pyproject.toml#L202 also how do I add commit hash (mentioned earlier)?

2023-12-14 13:04 UTC, kratman commented
@prady0t How is this coming along?

2023-12-14 14:30 UTC, prady0t commented
> @prady0t How is this coming along?

Sorry for not being active. I had exams then had to travel back home. Was working on this just today, will complete this by EOD.

2023-12-14 17:22 UTC, kratman commented
No rush, just curious since you were close

2023-12-14 17:31 UTC, prady0t commented
Done! Please have a look.

2023-12-14 17:42 UTC, agriyakhetarpal commented
After you reset your branch locally you pulled the changes in it that were present on GitHub instead of a force push (I think). This is why 101 or so commits are showing up (probably due to a broken merge commit, the presence of which would have fixed it otherwise)

2023-12-14 17:47 UTC, prady0t commented
I might have to close this PR as well. What do you think?

2023-12-14 18:01 UTC, agriyakhetarpal commented
You can reset your branch and keep working on the same PR using the instructions posted above, no worries! Otherwise, you can undo your commits till https://github.com/pybamm-team/PyBaMM/pull/3579/commits/75b58bc50646e5599027e73f5c8254714a20754e is the last commit.

2023-12-14 18:10 UTC, kratman commented
@prady0t You are so close. If you want I can post the full set of commands to do it with reset/cherry pick. The general procedure I would follow is
- Reset to origin/main
- Cherry pick your pre-commit config changes from this branch on your fork's origin (origin/new-format-fix)
- Run pre-commit, commit formatting changes, copy the commit hash
- Add the formatting changes hash to the ignored revs, and commit that change
- Force push to this branch

2023-12-14 18:11 UTC, Saransh-cpp commented
You can also `git log` the hashes of your last 4 commits, reset everything in this branch, and then `git cherry-pick` those 4 commits using their hashes.

This would be a nice git exercise but please feel free to open a new PR if you feel that would be better.

2023-12-14 18:49 UTC, prady0t commented
Did this work? I basically just did this:
```
git reset --hard 75b58bc  
git push origin -f
```

2023-12-14 18:53 UTC, agriyakhetarpal commented
Yes, you are back on track. All that is left is to follow the instructions in https://github.com/pybamm-team/PyBaMM/pull/3579#issuecomment-1847220060

2023-12-14 18:57 UTC, prady0t commented
> Yes, you are back on track. All that is left is to follow the instructions in [#3579 (comment)](https://github.com/pybamm-team/PyBaMM/pull/3579#issuecomment-1847220060)

But all those commits are already there and ci test have passed as well. Do I have to do it again?

2023-12-14 19:10 UTC, agriyakhetarpal approved these changes
We should be done, then – these changes look great! Thanks, @prady0t!

2023-12-14 19:10 UTC, agriyakhetarpal commented on pybamm/solvers/processed_variable.py
> +                            f"Shape not recognized for {base_variables[0]} "
```suggestion
                            f"Shape not recognized for {base_variables[0]}"
```

2023-12-14 19:24 UTC, Saransh-cpp approved these changes
Looks good, thanks @prady0t! I could see some formatting issues but hopefully they'll be resolved once `ruff format` is added in.

2023-12-14 19:24 UTC, Saransh-cpp commented on pyproject.toml
>    "YTT",         # flake8-2020
```suggestion
  "UP",           # pyupgrade
  "YTT",         # flake8-2020
```

2023-12-14 19:24 UTC, Saransh-cpp commented on pyproject.toml
> +    "UP007",     # For pyupgrade
```suggestion
  "RUF002",      # Docstring contains ambiguous
  "UP007",       # For pyupgrade
```

2023-12-14 19:24 UTC, Saransh-cpp commented on pybamm/discretisations/discretisation.py
> -class Discretisation(object):
Nice, getting rid of Python 2!

2023-12-14 19:24 UTC, Saransh-cpp commented on pybamm/discretisations/discretisation.py
> +            raise TypeError(f"""y_slices should be dict, not {type(value)}""")
```suggestion
            raise TypeError(f"y_slices should be dict, not {type(value)}")
```

2023-12-14 19:24 UTC, Saransh-cpp commented on pybamm/models/full_battery_models/base_battery_model.py
> +                    """
```suggestion
                f"must use surface formulation to solve {self!s} with hydrolysis"
```

2023-12-14 19:41 UTC, prady0t commented
Thanks for being so supportive everyone 😄 .

2023-12-14 19:41 UTC, kratman approved these changes

2023-12-14 19:43 UTC, kratman commented
https://github.com/all-contributors please add @prady0t for infrastructure

2023-12-14 19:45 UTC, kratman commented
@all-contributors please add @prady0t for infrastructure

2023-12-15 09:42 UTC, Saransh-cpp commented on pyproject.toml
>    "YTT",         # flake8-2020
nitpicking 🙂 
```suggestion
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
```

2023-12-15 16:54 UTC, merged