Added test to check if simulation has been solved in `simulation.py` and `batch_study.py`
pybamm-team/PyBaMM pull request #3795
Opened 2024-02-01 09:30 UTC by prady0t

# Description

Simple check for if simulations have been solved or not.

Fixes #3725 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-02-01 14:56 UTC, Saransh-cpp requested changes
Thanks, @prady0t! Looks really nice! A couple of comments below -

2024-02-01 14:56 UTC, Saransh-cpp commented on pybamm/batch_study.py
> +        if not self.sims:
You could do something like -
```suggestion
        if not hasattr(self, "sims"):
```
I think this should work.

2024-02-01 14:56 UTC, Saransh-cpp commented on pybamm/batch_study.py
> +        self.sims = []
Initializing this in `__init__` would be redundant. We can keep this in its original place.

2024-02-01 14:56 UTC, Saransh-cpp commented on pybamm/batch_study.py
> +        self.sims = []
and using `hasattr` will still work

2024-02-01 18:00 UTC, prady0t commented
@Saransh-cpp I've done the suggested changes here.

2024-02-01 18:45 UTC, Saransh-cpp approved these changes
Thanks, @prady0t! Looks good to me!

2024-02-02 19:00 UTC, agriyakhetarpal commented
Should we add a CHANGELOG entry here?

2024-02-02 19:04 UTC, kratman commented
> Should we add a CHANGELOG entry here?

I think it is a small enough change that it does not need it. However that one test keeps failing and I doubt it is due to this small PR. Should we open a PR for that or do you already know what is happening?

2024-02-02 19:26 UTC, agriyakhetarpal commented
> Should we open a PR for that or do you already know what is happening?

No worries, it looks like it was coming from a cached wheel for `scikits.odes` – I deleted the caches and the test passed this time. Let's merge

2024-02-02 19:26 UTC, merged

2024-02-02 19:35 UTC, agriyakhetarpal commented
@all-contributors please add @prady0t for code, test