Fix broken `Open in Colab` badges linked to example notebooks
pybamm-team/PyBaMM pull request #3818
Opened 2024-02-14 18:37 UTC by arjxn-py

# Description

This issue aims to fix broken `Open in Colab` badges on docs.pybamm.org

Fixes #3817 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-02-14 19:16 UTC, kratman approved these changes
The change looks reasonable and it works in the docs build. I did not test it locally though, not sure if that matters

2024-02-14 19:26 UTC, arjxn-py commented
I believe that the docs build in this PR is unrelated as it's not stable build. Nice to have @agriyakhetarpal review as well, I hope merging this to develop would fix the badges without having to update `v24.1` branch.

2024-02-14 21:02 UTC, agriyakhetarpal requested changes
This should be just `/blob/`, rather than both `/tree/blob/`. 

i.e., this link works: https://githubtocolab.com/pybamm-team/PyBaMM/blob/v24.1/docs/source/examples/notebooks/getting_started/tutorial-3-basic-plotting.ipynb

but these don't:
 https://githubtocolab.com/pybamm-team/PyBaMM/tree/v24.1/docs/source/examples/notebooks/getting_started/tutorial-3-basic-plotting.ipynb (the original, failing one)

and

https://githubtocolab.com/pybamm-team/PyBaMM/blob/tree/v24.1/docs/source/examples/notebooks/getting_started/tutorial-3-basic-plotting.ipynb (current modification)

Sadly, this won't fix the link failure for the 24.1 release. Wish there were a reliable method to test such links, since I don't think even #3387 would cover this scenario.

Please feel free to merge after applying the request changes!

2024-02-14 21:15 UTC, agriyakhetarpal approved these changes

2024-02-14 21:16 UTC, arjxn-py commented
> Sadly, this won't fix the link failure for the 24.1 release. I wish there were a reliable method to test such links, since I don't think even #3387 would cover this scenario.

Would it be nicer to open a separate issue about this other than #3387 where we could also further discuss about exploratory ways to cover the issue?

2024-02-14 21:25 UTC, merged

2024-02-15 04:54 UTC, agriyakhetarpal commented
> Would it be nicer to open a separate issue about this other than #3387 where we could also further discuss about exploratory ways to cover the issue?

I think this issue is minor enough to say that it won't get repeated again

2024-02-15 09:19 UTC, arjxn-py commented
The badges are still not fixed for the stable version, should we cherry-pick this to `v24.1`?

2024-02-15 10:26 UTC, agriyakhetarpal commented
> The badges are still not fixed for the stable version, should we cherry-pick this to `v24.1`? or maybe wait for next rc

I surfed some links and I am understanding that RTD _does_ build the documentation via GitHub webhooks from repository tags. So, yes, I think cherry-picking this commit to the v24.1 tag should fix this on the `stable` version of the documentation. I will leave this up to what @Saransh-cpp thinks about this, though my preference would be to wait until the next RC. Maybe Google Colab or https://githubtocolab.com changed something from their end, because I remember that this had worked when I had implemented it (which is why I kept it as `tree` instead of `blob`).

2024-02-15 10:33 UTC, Saransh-cpp commented
I won't suggest moving the tag around. The maximum we can do is create a `v24.1post1` release, but I don't think that is required. Let's keep this for the next release.