Remove python-idaklu
pybamm-team/PyBaMM pull request #4326
Opened 2024-08-08 14:36 UTC by pipliggins

# Description

Removes the legacy python-idaklu solver which calls IDAKLU but returns back to python for certain functions. With recent improvements to IDAKLU this can now be removed.

Reduces the number of solvers we need to maintain.

Fixes #4223 

## Type of change

- [ ] Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-08-22 14:46 UTC, kratman commented
@pipliggins What still needs to be done for this PR?

2024-08-22 15:41 UTC, pipliggins commented
@kratman I think it's pretty much ready to go. The only query (which I realise now I hadn't actually voiced anywhere, whoops) is what to do about some indirect changes flagged by codecov which leave several lines of code untested after removing the solver.
It's not clear to me that those lines are specific to the old IDAKLU solver, in fact I'm pretty sure at least some of them shouldn't be, but I've found it hard to work out why they aren't covered by other tests, or how to reach those lines by adding new ones. (@martinjrobins any thoughts as well?)

2024-08-22 16:14 UTC, kratman commented
> The only query (which I realise now I hadn't actually voiced anywhere, whoops) is what to do about some indirect changes flagged by codecov which leave several lines of code untested after removing the solver. It's not clear to me that those lines are specific to the old IDAKLU solver, in fact I'm pretty sure at least some of them shouldn't be, but I've found it hard to work out why they aren't covered by other tests, or how to reach those lines by adding new ones

I think a lot of the test coverage is actually indirect. Some tests are only run with specific parameter sets or certain modes might only be run in a test for something unrelated. Ultimately as large functions get broken up into smaller once, this should get better.

Personally a loss of a little coverage does not bother me, but I do wonder if some of the lost coverage could be from logic that was catching rare edge cases.

2024-08-22 18:44 UTC, kratman reviewed
Just minor suggestions. The coverage changes seem fairly small, but @martinjrobins should take a look as well

2024-08-22 18:44 UTC, kratman commented on src/pybamm/solvers/idaklu_solver.py
> +        # rtol = self.rtol
If this is not needed anymore then it should be removed
```suggestion
```

2024-08-22 18:44 UTC, kratman commented on src/pybamm/solvers/idaklu_solver.py
> +            raise pybamm.SolverError("The python idaklu solver is no longer supported")
```suggestion
            raise pybamm.SolverError("Unsupported IDAKLU solver configuration.")
```

2024-08-22 18:44 UTC, kratman commented on src/pybamm/solvers/idaklu_solver.py
> +        ):
Alternatively the `self._options["jax_evaluator"] != "iree"` check could be added here:
```
        if model.convert_to_format == "jax":
            mass_matrix = model.mass_matrix.entries.toarray()
```

2024-08-22 19:37 UTC, agriyakhetarpal commented on src/pybamm/models/base_model.py
> +        - "jax": convert into JAX expression tree
I think this was a missing docstring that was never added before this PR

2024-08-22 19:43 UTC, kratman commented on src/pybamm/models/base_model.py
> +        - "jax": convert into JAX expression tree
Yeah updating the docs is always good. Just checking if there was added functionality somewhere in the PR to go along with it

2024-08-22 19:55 UTC, martinjrobins requested changes
Thanks @pipliggins, looking forward to no longer supporting this :) The codecov errors reminded me: now the python idaklu solver is removed we no longer use the python evaluator in sensitivitiy calculations, this is why some of these covereage errors. I would suggest to raise an error after line 1471 in base_solver.py (if model.calculate_sensitivities is true) saying that sensitivity calculation for the python evaluator is no longer supported, since we don't want to add tests for this. We can then remove this if statement from coverage with `# pragma: no cover`

2024-08-23 09:11 UTC, pipliggins commented on src/pybamm/models/base_model.py
> +        - "jax": convert into JAX expression tree
No added functionality, just noticed the description was missing as I worked my way though relevant sections

2024-08-26 06:54 UTC, martinjrobins approved these changes
thanks @pipliggins, this looks good to me. Once the conflicts are resolved it can be merged.

2024-08-27 11:43 UTC, pipliggins commented
@martinjrobins @kratman Conflicts have been resolved, this is ready to merge. Thanks!

2024-08-27 18:17 UTC, kratman approved these changes
Thanks looks good

2024-08-27 18:18 UTC, merged