IDA adaptive time stepping
pybamm-team/PyBaMM pull request #4351
Opened 2024-08-16 13:05 UTC by MarcBerliner

# Description

[to be written]

Fixes #4312

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] Optimization (back-end change that speeds up the code)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

2024-08-16 21:39 UTC, valentinsulzer reviewed
Looks good to me other than some very minor comments. I have a feeling there are several bits of code we'll be able to refactor once this is in as the default everywhere but that can be a job for later. As usual will leave the C++ code to others to review

2024-08-16 21:39 UTC, valentinsulzer commented on src/pybamm/experiment/step/base_step.py
> +        if solver._supports_interp:
We don't do this well in general, but private methods should only be accessed from within the same file/class - in this case each `Solver` class should implement a property `supports_interp` in order to make it truly read-only.

2024-08-16 21:39 UTC, valentinsulzer commented on src/pybamm/experiment/step/base_step.py
> +        period, t_interp willbe set to return the solution at the end of each period
```suggestion
        period, t_interp will be set to return the solution at the end of each period
```

2024-08-16 21:39 UTC, valentinsulzer commented on src/pybamm/solvers/base_solver.py
> +        self._supports_interp = False
make this a property instead (and we should have made `ode_solver` and `algebraic_solver` properties too so might as well do that while you're there)

2024-08-19 12:18 UTC, martinjrobins requested changes
Really great work @MarcBerliner, this looks excellent and some really great speed-ups! :) I've suggested a few changes below that need to be fixed but mostly minor. One general question I had: many of the idaklu tests use a dense t_eval and an identical t_interp, which is now the "slow" way of running the solver. When not specificly testing the interpolation code, I would use the most efficient / standard way of running `solver.solve`, which I believe would be `t_eval = [start, stop]` and `t_interp = None` or `t_interp = np.linspace(start, stop, N)`?

2024-08-19 12:18 UTC, martinjrobins commented on src/pybamm/simulation.py
> +        t_interp : None, list or ndarray, optional
`t_interp` is not passed to  `solver.solve` for the case `self.operating_mode in ["without experiment", "drive cycle"]`

2024-08-19 12:18 UTC, martinjrobins commented on src/pybamm/simulation.py
> +        t_interp : None, list or ndarray, optional
also, does the docstring for t_eval need to be updated? It currently says "Can be provided as an array of times at which to return the solution", but this is the role of `t_interp` now.

2024-08-20 16:18 UTC, MarcBerliner commented on src/pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP.inl
> +      // IDA sometimes returns an identical time point twice
I'm not sure if this is an IDA bug, but this issue is documented in [Sundials.jl](https://github.com/SciML/Sundials.jl/blob/d7e83c086d40e1b5b7ce470cccfea5dfd5586ec3/src/common_interface/solve.jl#L1418):
```
# NB: CVode, ARKode may warn and then recover if integrator.t == integrator.tprev so don't flag this as an error 
```
Whenever I've encountered this issue it's due to an ill-posed model, which can happen a lot in parameter estimation. It does continue the solve, but in my experience it uses miniscule time steps that cause floating point arithmetic issues and continues to use these tiny steps until it exhausts the maxiters.

2024-08-20 17:54 UTC, MarcBerliner commented
> One general question I had: many of the idaklu tests use a dense t_eval and an identical t_interp, which is now the "slow" way of running the solver. When not specificly testing the interpolation code, I would use the most efficient / standard way of running `solver.solve`, which I believe would be `t_eval = [start, stop]` and `t_interp = None` or `t_interp = np.linspace(start, stop, N)`?

@martinjrobins good point. The most efficient way to run it is using the `t_eval = [start, stop]` and `t_interp = None`. A current limitation with this PR is that we do not have the Hermite interpolator available in python (adding it is difficult), so all the post-interpolation tests like `sol[v](t)` use linear interpolation, which is less accurate. I changed most tests to use `t_interp = np.linspace(start, stop, N)`, which uses the Hermite interpolator.

Once [this PR merges](https://github.com/pybamm-team/PyBaMM/pull/4326), we can fully migrate all the tests to using `t_eval = [start, stop]` and `t_interp = np.linspace(start, stop, N)`. When we have more accurate post-interpolation, we can then change it to `t_eval = [start, stop]` and `t_interp = None`

2024-08-22 20:08 UTC, martinjrobins requested changes
thanks @MarcBerliner, just a few more minor changes below

2024-08-22 20:08 UTC, martinjrobins commented on src/pybamm/solvers/c_solvers/idaklu/common.cpp
> +#include <idas/idas.h>                 /* prototypes for IDAS fcts., consts.    */
all these headers are already included in common.hpp and so are not needed here

2024-08-22 20:08 UTC, martinjrobins commented on src/pybamm/solvers/base_solver.py
> +    def ode_solver(self, value):
I don't think we need a setter here as ode_solver should be read-only for users

2024-08-22 20:08 UTC, martinjrobins commented on src/pybamm/solvers/base_solver.py
> +    def algebraic_solver(self, value):
same here

2024-08-22 20:08 UTC, martinjrobins commented on src/pybamm/solvers/base_solver.py
> +    def supports_interp(self, value):
and here

2024-08-22 20:08 UTC, martinjrobins commented on src/pybamm/solvers/base_solver.py
> +    def ode_solver(self, value):
internally we can still set this via `self._ode_solver = X`

2024-08-23 08:06 UTC, martinjrobins approved these changes
Looks great, thanks @MarcBerliner

2024-08-23 18:36 UTC, merged