Support sensitivities for Simulations
pybamm-team/PyBaMM pull request #4415
Opened 2024-09-04 15:56 UTC by martinjrobins

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #3834 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] 
# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

2024-09-11 14:07 UTC, brosaplanella approved these changes
Looks good to me! Asking @MarcBerliner to review the PR too, as he knows a lot more about this than me.

2024-09-11 20:24 UTC, martinjrobins commented on CHANGELOG.md
> +- Added sensitivity calculation support for `pybamm.Simulation` and `pybamm.Experiment` ([#4415](https://github.com/pybamm-team/PyBaMM/pull/4415))
oops, I missed that header, thanks @kratman, I'll fix that

2024-09-12 18:42 UTC, MarcBerliner requested changes
Thanks Martin! This is great, just a few minor comments on the code.

There are some experimental setups where a linearized sensitivity analysis might produce inaccurate results. Sequential experiment steps with a fixed end time will always work correctly. However, sequential steps with event-based termination conditions (like max voltage) may give the correct answer since the end time of each step is indeterminate and may change wrt the parameters. The only situation where an experiment step with an event-based termination is valid is if it’s the final step in the experiment. It would be nice to add a check for this in the code.

2024-09-12 18:42 UTC, MarcBerliner commented on src/pybamm/simulation.py
> +                pass
Can we check with `has_key` instead of the try/except block?

2024-09-12 18:42 UTC, MarcBerliner commented on tests/unit/test_solvers/test_casadi_solver.py
> +        print(solution.y.shape)
Debug line left in

2024-09-13 08:55 UTC, martinjrobins commented
> There are some experimental setups where a linearized sensitivity analysis might produce inaccurate results. Sequential experiment steps with a fixed end time will always work correctly. However, sequential steps with event-based termination conditions (like max voltage) may give the correct answer since the end time of each step is indeterminate and may change wrt the parameters. The only situation where an experiment step with an event-based termination is valid is if it’s the final step in the experiment. It would be nice to add a check for this in the code.

Yea, its a good point. For event-based termination conditions there would be an additional term in the sensitivity equations which we are assuming is close to zero. In our particular case where the model changes over the event I'm not sure if this term can even be defined, although it would be interesting to look into this further. I'd be reluctant to make this an error, and to allow users to still use this for event-based terminations. As long as the additional term is small the sensitivities can still be used within, for example, an optimisation algorithm that is robust to errors in the gradient (which many are). I'll put something in the docstrings to warn users about this, and I'll do a run-time check and emit a warning if the experiment contains an event-based termination, how does that sound?

2024-09-13 11:03 UTC, MarcBerliner commented
> I'll put something in the docstrings to warn users about this, and I'll do a run-time check and emit a warning if the experiment contains an event-based termination, how does that sound?

Sounds good to me.

2024-09-13 11:04 UTC, MarcBerliner approved these changes

2024-09-13 15:44 UTC, merged

2024-10-30 18:34 UTC, itsjacobhere commented
This feature would enable gradient computation while using `pybamm.Experiment` to describe a current profile right? Has this been implemented yet? Thanks!