Domain degradation parameters
pybamm-team/PyBaMM pull request #4463
Opened 2024-09-24 14:00 UTC by DrSOKane

# Description

Added domains to the SEI and plating degradation parameters, allowing them to be different on each electrode. This is useful for negative half-cells, where the positive electrode is graphite and the negative electrode is lithium metal.
* The names of almost all SEI and plating parameters have been changed, making this **a breaking change**
* All built-in parameter sets have been updated to work with the new syntax
* The example notebook for half-cells has been updated to showcase the new feature. By adjusting the SEI parameters on each electrode, it is shown that SEI on the lithium metal electrode can provide enough resistance to prevent plating on the graphite electrode.
* A parameter set for a half-cell with a graphite+silicon composite has been added. I considered adding this to the example notebook but it is already very long and I still don't have much experience using the composite model.

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-09-24 20:29 UTC, valentinsulzer reviewed
Thanks Simon, given that this is a breaking change I'd be inclined to wait and lump it in with the breaking changes that will come from the parameters refactor ... @BradyPlanden @kratman when is that likely to come in?

2024-09-24 22:26 UTC, kratman requested changes

2024-09-24 22:26 UTC, kratman commented on CHANGELOG.md
>  - Added phase-dependent particle options to LAM #4369
PR #4417 is still open this probably should not be in the log. Not sure if those changes are also in here, but we should probably either separate these PRs or close the other PR.

2024-09-25 12:25 UTC, DrSOKane commented
This PR follows on from PR #4417 and does indeed contain everything from there. I've decided to convert this PR to draft and reopen when #4417 - which has far more use cases in practice - is complete.

2025-07-02 17:30 UTC, kratman commented
@DrSOKane Are you still working on this?

2025-07-03 21:20 UTC, DrSOKane commented
> @DrSOKane Are you still working on this?

Not recently. #4869 is much higher priority.

2025-07-03 22:16 UTC, kratman commented
Can we close this one for now, there are a huge number of conflicts

2025-07-03 22:18 UTC, closed without merging