Download IDAKLU from pybammsolvers
pybamm-team/PyBaMM pull request #4487
Opened 2024-10-03 16:47 UTC by kratman

# Description

This will separate the IDAKLU C++ code from pybamm.

Fixes #3564
Fixes #4611

This ticket is something that can be handled in the other repo
Closes #3603 

## Type of change

This should speed up CI by skipping the build of the C++ code.

- [x] Optimization (back-end change that speeds up the code)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

2024-10-03 17:15 UTC, kratman commented
A new link error cropped up, but it looks like we could get a lot of savings on time with this update

2024-10-03 18:51 UTC, agriyakhetarpal commented
The linkage error is the same one as #3783, coming from CasADi's plugin system. I am not sure if it's worth fixing it, since it was fixed by @martinjrobins for the linear interpolant case by dropping down to Python but IIRC there wasn't a way in CasADi for doing it for the cubic

2024-10-03 20:18 UTC, kratman commented
@agriyakhetarpal Yeah I was looking at that issue as well. As far as I can tell CasADI sets a path for plugins. I am trying to see if there is a decent workaround since this was part of #4464

My guess is that the wheels for the next release will be broken as well, but I have not confirmed it yet

2024-10-03 20:29 UTC, agriyakhetarpal commented
There is a workaround for Linux and macOS, but not for Windows (different toolchain); sadly, it's not decent enough to include. I think I'll raise a PR upstream in CasADi to get one part of the linkage going and see if we can migrate to a non-MSVC toolchain (which can potentially help fix this later on). It's been on my list of things to do for a while, but I've yet to do it.

2024-10-03 22:13 UTC, kratman commented
This is fixed locally with this: `export CASADIPATH=.venv/lib/python3.12/site-packages/casadi`

2024-10-03 23:23 UTC, agriyakhetarpal commented
> This is fixed locally with this: `export CASADIPATH=.venv/lib/python3.12/site-packages/casadi`
> 

Yes, won't work with Windows

2024-11-06 16:46 UTC, martinjrobins commented
I had a look at this. The linker error is the same as I came across for the case of linear interpolation. The solution there was to swap to using the direct casadi function rather than their plugin system, which won't work if the casadi function is evaluated in C++ for windows as we compile everything statically. 

I think I might be able to access the direct bspline interface by calculating the spline coefficients in scipy and then use the casadi `Function.bspline` function to construct a bspline. Cross fingers this doesn't use the plugin system anywhere!

2024-11-06 16:51 UTC, kratman commented
> I had a look at this. The linker error is the same as I came across for the case of linear interpolation. The solution there was to swap to using the direct casadi function rather than their plugin system, which won't work if the casadi function is evaluated in C++ for windows as we compile everything statically.
> 
> I think I might be able to access the direct bspline interface by calculating the spline coefficients in scipy and then use the casadi `Function.bspline` function to construct a bspline. Cross fingers this doesn't use the plugin system anywhere!

Yeah I was going to approach this by seeing if I could just change the build itself. It is something that should work if we are compiling and delivering everything correctly. If that does not work, then I will look at workarounds for interpolation

2024-11-06 16:52 UTC, kratman commented
I expect to work on this again next week, I have been caught up with other stuff

2024-11-21 10:59 UTC, martinjrobins commented
looks like there is still issues with the idaklu jax solver on windows, I can look into these?

2024-11-21 14:55 UTC, martinjrobins commented
I tried to figure this one out today but no luck :( It's crashing with a fatal exception when jax tries to jit compile, I'm still in the dark as to why. It might be a threading issue as the problem is intermittant (occurs in about 95% of test runs). It might be cause with some interaction with pytest because when I copy the test into a stand-alone script it works fine

2024-11-21 17:19 UTC, agriyakhetarpal commented
For a stopgap solution, we can isolate these tests into their own xdist_group and allow only one worker to touch them at a time.

2024-11-21 18:05 UTC, kratman commented
> For a stopgap solution, we can isolate these tests into their own xdist_group and allow only one worker to touch them at a time.

Yeah that is my fallback option.

I want to take a closer look at the linking/delivery as well. We have failures on windows when you download the wheels:
- pybammsolvers has some crashes workers
- my i5 (without AVX-512 instructions) has ~45 test failures on both 24.9.0 and 24.11.0 when running tests with the wheels
- A colleague's i7 (with AVX-512 instructions) has ~25 test failures on both 24.9.0 and 24.11.0 when running tests with the wheels

So it appears that the tests are working when you test in the build environment, but not in a different environment. I will be digging into this more and see what I come up with

2024-11-22 09:51 UTC, jsbrittain commented
Hi - I took a very quick look at this yesterday and agree that it seems to be a threading issue. More specifically, `jaxify()` can only be called once per solver instance (this is the first test), which then caches the full solve result so the jax-wrapper can query samples without repeatedly re-running the solver. My suspicion is that running these tests in parallel is causing test pollution, probably because the test script currently instantiates the solver and jax wrapper objects at the start of the test script, not as a fixture for each test (although the ubuntu tests should also be failing?). Refactoring the tests with fixtures would be good to see if that resolves things - I can take a look at that if you like but if I'm right then the `xdist_group` solution should also work if you need a quick fix. I can't remember the precise details as to why we can't jaxify more than once per object, but I do remember that it was more complex than just the cache issue (something to do with the jax primitives...).

2024-12-26 19:10 UTC, kratman commented
Testing out the skips and test refactor now with CI. I have some docs stuff to update then this should be mostly ready to go. I will do one more update to pybammsolvers to make sure that the versions of IDAKLU match

2024-12-26 21:47 UTC, kratman commented
Tests pass, just need to do some documentation fixes

2024-12-27 18:59 UTC, kratman commented
Additional documentation will be added to the pybammsolvers repo

2024-12-27 19:43 UTC, kratman commented
@MarcBerliner, @martinjrobins Ok I think this is finally working. I am working on tests and docs for the other repo now

2025-01-02 10:21 UTC, Saransh-cpp reviewed
This is fantastic. Took a quick view and it looks good overall!

2025-01-02 10:21 UTC, Saransh-cpp commented on docs/source/user_guide/installation/gnu-linux-mac.rst
> -
I think `pybammsolvers` is not yet available on conda-forge? This can be updated with something better near the "required dependencies" section.

2025-01-02 10:21 UTC, Saransh-cpp commented on docs/source/user_guide/installation/index.rst
>     The ``pybamm`` package on conda-forge installs PyBaMM with all the `required and optional dependencies <#dependencies>`_ available on conda-forge.
The required dependencies section should be updated to include `pybammsolvers`.

2025-01-02 11:49 UTC, agriyakhetarpal commented on docs/source/user_guide/installation/gnu-linux-mac.rst
> -
cc @prady0t: we will now like to get the IDAKLU solver packaged and ready, since the v25.1 release is fast approaching. So, while it is okay to wait for a while (since PyBaMM's conda-forge package is downloaded much less than the PyPI wheels, and feedstocks sometimes do tend to lag behind releases), it would be great if your work could be expedited so that both distributions are at par soon after the release.

Please feel free to [start a new feedstock](https://conda-forge.org/docs/maintainer/understanding_conda_forge/feedstocks/#initialization) for `pybammsolvers` and ping Saransh and/or me where you have any questions with the recipe!

2025-01-02 13:56 UTC, prady0t commented on docs/source/user_guide/installation/gnu-linux-mac.rst
> -
Just to be clear, `pybammsolvers` is all the C++ part related to IDAKLU solver. For packaging pybamm with IDAKLU, we can specify one of the dependencies as `pybamsolvers` in pybamm feedstock and later continue with building `suitsparse` and `sundials`(Which I'm already been trying for a few days)

And for that, we need to package `pybammsolvers` as a conda-forge recipe, and hence a new feedstock is needed.

Am I correct?

2025-01-02 14:10 UTC, kratman commented on docs/source/user_guide/installation/gnu-linux-mac.rst
> -
@prady0t pybammsolvers should have all of the C++ code that is normally distributed with PyBaMM, so suitesparse and sundials are being built there. It should be the only C++ requirement for PyBaMM after this PR is done

What are the tickets for the suitespares and sundials work? I am probably going to need to do something there, and want to see if work is being duplicated

2025-01-02 14:17 UTC, kratman commented on docs/source/user_guide/installation/index.rst
>     The ``pybamm`` package on conda-forge installs PyBaMM with all the `required and optional dependencies <#dependencies>`_ available on conda-forge.
Ok I will fix this

2025-01-02 14:18 UTC, prady0t commented on docs/source/user_guide/installation/gnu-linux-mac.rst
> -
I was trying to build `suitsparse` and `sundials` as extension modules in pybamm feedstock. https://github.com/conda-forge/pybamm-feedstock/issues/65

2025-01-02 14:27 UTC, kratman commented on docs/source/user_guide/installation/index.rst
>     The ``pybamm`` package on conda-forge installs PyBaMM with all the `required and optional dependencies <#dependencies>`_ available on conda-forge.
Done. Maintaining that list seems like a bit of wasted effort. We should probably just link people to our pyproject.toml file or something. Nobody needs to manually install that list of dependencies, they are just installed by pip or conda

2025-01-02 14:28 UTC, kratman commented on docs/source/user_guide/installation/gnu-linux-mac.rst
> -
@Saransh-cpp I assumed that pybammsolvers would be uploaded to conda before the release, so I hope we don't need a note about it. A goal is to also switch IDAKLU to be the default solver (I have a branch locally, but have not pushed yet)

2025-01-03 11:21 UTC, Saransh-cpp commented on docs/source/user_guide/installation/gnu-linux-mac.rst
> -
That makes sense, thanks for the clarification!

2025-01-03 11:38 UTC, agriyakhetarpal commented on docs/source/user_guide/installation/gnu-linux-mac.rst
> -
> I assumed that pybammsolvers would be uploaded to conda before the release

This means we have around ~2 weeks, echoing Eric's message from Slack (if we need PyBaMM's v25.1 `conda-forge` release to be on time and as close as possible to the PyPI release, that is).

2025-01-03 11:52 UTC, agriyakhetarpal requested changes

2025-01-03 11:52 UTC, agriyakhetarpal commented on .github/workflows/benchmark_on_push.yml
> +          python -m uv pip install --upgrade pip wheel setuptools wget numpy
```suggestion
```

I don't think even this should be needed now, `asv` sets up and manages environments automatically from its config file.

2025-01-03 11:52 UTC, agriyakhetarpal commented on .github/workflows/periodic_benchmarks.yml
> +          python -m uv pip install --upgrade pip wheel setuptools wget numpy
```suggestion
```

2025-01-03 11:52 UTC, agriyakhetarpal commented on .github/workflows/publish_pypi.yml
> +          CIBW_BEFORE_BUILD_LINUX: python -m pip install setuptools wheel
```suggestion
          CIBW_BEFORE_BUILD_LINUX: python -m pip install setuptools
```

From #4652

2025-01-03 11:52 UTC, agriyakhetarpal commented on .github/workflows/publish_pypi.yml
> +          CIBW_BEFORE_BUILD: python -m pip install setuptools wheel delocate
```suggestion
          CIBW_BEFORE_BUILD: python -m pip install setuptools delocate
```

2025-01-03 11:52 UTC, agriyakhetarpal commented on CHANGELOG.md
> +  easier. ([#4487](https://github.com/pybamm-team/PyBaMM/pull/4487))
```suggestion
- Moved the IDAKLU solver to a standalone `pybammsolvers` package. This will
  make PyBaMM a pure Python package and make installing and using the solver
  easier. ([#4487](https://github.com/pybamm-team/PyBaMM/pull/4487))
```

(nit)

2025-01-03 11:52 UTC, agriyakhetarpal commented on benchmarks/different_model_options.py
> -
This will make the IDAKLU solver non-optional, is this also intended here? This would cause non-supported platforms such as Linux arm64 (which we provide Docker images for) try to compile `pybammsolvers` from the sdist, which is going to be broken until https://github.com/pybamm-team/pybammsolvers/pull/7 is merged.

 I think it's better to split both tasks (separating the solver, and making the solver the default) in two separate PRs.

2025-01-03 11:52 UTC, agriyakhetarpal commented on pyproject.toml
> +    "wheel",
```suggestion
```

Now dropped with #4652

2025-01-03 11:52 UTC, agriyakhetarpal commented on pyproject.toml
> +    "pybammsolvers",
This makes it a non-optional dependency, and is a breaking change as well – please see my comment above.

2025-01-03 11:52 UTC, agriyakhetarpal commented on scripts/Dockerfile
> +RUN uv pip install --upgrade setuptools wget
```suggestion
```

2025-01-03 11:52 UTC, agriyakhetarpal commented on src/pybamm/solvers/idaklu_solver.py
> +    idaklu_imported = False
Same as above

2025-01-03 11:52 UTC, agriyakhetarpal commented on src/pybamm/solvers/idaklu_jax.py
> +
The IDAKLU solver is optional here, but `pybammsolvers` also needs to be an optional dependency for this to work correctly and be guarded under `pybamm[idaklu]` or a similar name (maybe `[solvers]` because the plan is to add CVODES too?)

2025-01-03 14:36 UTC, kratman commented on benchmarks/different_model_options.py
> -
Yeah changing the default solver is intended to be a separate task.

I thought the linux Arm64 stuff was already fixed. I go back to working on that

2025-01-03 14:37 UTC, kratman commented on src/pybamm/solvers/idaklu_jax.py
> +
I had this in here for testing and error handling. I think there is probably other cleanup that can be done as well.

2025-01-03 14:56 UTC, agriyakhetarpal commented on benchmarks/different_model_options.py
> -
Sure. The last time I worked on Linux arm64, cross-compilation wasn't helpful with SuiteSparse's symbols turning up missing, and CasADi faced https://github.com/dockcross/dockcross/issues/780 when I tried compiling under QEMU. But maybe the situation has improved by a lot now...

2025-01-07 16:56 UTC, kratman commented on src/pybamm/solvers/idaklu_solver.py
> +    idaklu_imported = False
Removed

2025-01-07 16:57 UTC, kratman commented on pyproject.toml
> +    "pybammsolvers",
The intention is to make it required, but not default yet

2025-01-07 16:58 UTC, kratman commented on benchmarks/different_model_options.py
> -
I am working on getting the scikit build up and running again while also looking at the conda-forge recipe. Hopefully those will resolve these issues

2025-01-07 17:48 UTC, agriyakhetarpal approved these changes
Yes, let's do that, @kratman. Linux arm64 is quite common but lacks readily available CI providers for OSS; Windows arm64 CI is not present either outside of Windows Arm dev boxes. FWIW, we can mark both platforms/architectures as unsupported for now and ask users to compile it themselves (the same as we did when macOS arm64 was not common).

Based on https://stackoverflow.com/a/64921347, we will have to wait a bit for PyBaMM 25.1 to be supported on conda-forge until https://github.com/conda-forge/staged-recipes/pull/28748 is resolved, but at the time if someone needs a new version of PyBaMM in a conda environment, they should be able to `pip`-install without any issues as long as their environment files specify that.

2025-01-07 18:00 UTC, kratman commented
Note: The changes from #4736 are not in pybammsolvers yet. The tests pass without the C++ side for now though. I am working on the pybammsolvers v0.0.5 release, but I have to do a bit of testing before it is ready. Hopefully I will finish that off today

2025-01-07 18:35 UTC, merged