Modifies `QuickPlot.plot` to take a list of times and show superimposed plots in case of 1D variables.
pybamm-team/PyBaMM pull request #4529
Opened 2024-10-20 14:10 UTC by medha-14

# Description
![image](https://github.com/user-attachments/assets/11ccacb3-fb33-458e-952f-04077d808626)

Fixes #4271 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-10-20 14:13 UTC, medha-14 commented
I will be working on adding different colors and a legend to the time plots to make them easier to differentiate. Please let me know if you have any suggestions for changes or improvements.

2024-10-21 13:23 UTC, medha-14 commented
I've added different colors to the time plots to make them easier to differentiate. Additionally, I've fixed some of the failing tests. Please suggest any changes or improvements.

![image](https://github.com/user-attachments/assets/31ad852c-8634-49d7-8614-3f0c63af41b4)

2024-10-22 13:51 UTC, arjxn-py reviewed
Awesome work @medha-14, you might just want to look into the `keyerror` that's being raised. 
You can try debugging that by running one test at a time something like - `pytest tests/unit/test_plotting/test_quick_plot.py::test_plot_1plus1D_spme
` Otherwise this looks really good.

2024-10-22 13:51 UTC, arjxn-py reviewed
Awesome work @medha-14, you might just want to look into the `keyerror` that's being raised. 
You can try debugging that by running one test at a time something like - `pytest tests/unit/test_plotting/test_quick_plot.py::test_plot_1plus1D_spme
` Otherwise this looks really good.

2024-10-22 14:03 UTC, kratman requested changes

2024-10-22 14:03 UTC, kratman commented on src/pybamm/plotting/quick_plot.py
> +                            color=self.colors[i],  # Different colors for plot lines
```suggestion
                            color=self.colors[i],
```

2024-10-22 14:03 UTC, kratman commented on tests/unit/test_plotting/test_quick_plot.py
> +        quick_plot.plot(0.0)
See above, but I don't see why we shouldn't be able to just pass in zero here

2024-10-23 12:36 UTC, medha-14 commented
I will work on fixing the failing tests. Should I also start working on adding new tests for this method?

2024-10-27 10:53 UTC, medha-14 commented
I have fixed the failing tests and tried to add tests ,  using a list of time in the plot function. I am open to work on any suggested improvements.

2024-11-02 10:26 UTC, medha-14 commented
Hi @kratman, could you review this and let me know what further changes I should make?

2024-11-11 11:28 UTC, medha-14 commented
Are there any other changes or improvements that I could make to further enhance the implementation?

2024-11-21 02:13 UTC, kratman commented
@medha-14 Sorry for the delay on this one, I will start reviewing this again

2024-11-21 02:19 UTC, kratman reviewed
Small findings, I will do a full review another day

2024-11-21 02:19 UTC, kratman commented on src/pybamm/plotting/quick_plot.py
> +        if isinstance(t, (int, float)):
Probably easier to do it this way
```suggestion
        if not isinstance(t, list):
```

2024-11-21 02:19 UTC, kratman commented on src/pybamm/plotting/quick_plot.py
> +        t : float or list
Can you also add the type annotation to the function signature?

2024-11-21 02:19 UTC, kratman commented on src/pybamm/plotting/quick_plot.py
> +                for _idx, t_single in enumerate(t):
The index does not appear to be used, so can we just simplify this?
```suggestion
                for t_single in t:
```

2024-11-21 02:22 UTC, kratman commented
Please also add a change log entry. Note that we are doing a release, so once #4598 is merged, there will likely be a merge conflict in the changelog

2024-11-21 20:57 UTC, kratman requested changes
This should be the last round of findings. Once these are resolved I will approve. Please double check that the figures still appear as you originally intended. Just good to do a visual double check. I will review those as well

2024-11-21 20:57 UTC, kratman commented on CHANGELOG.md
> +- Modified `quick_plot.plot` to accept a list of times and generate superimposed graphs for specified time points.([#4529](https://github.com/pybamm-team/PyBaMM/pull/4529))
This will have to move to the unreleased section due to the release this morning

2024-11-21 20:57 UTC, kratman commented on src/pybamm/plotting/quick_plot.py
> +                        f"'{variable_tuple[0]}' has domain '{domain}', but '{variable_tuple[ idx]}' has domain '{variable.domain}'"
Guessing this was a typo
```suggestion
                        f"'{variable_tuple[0]}' has domain '{domain}', but '{variable_tuple[idx]}' has domain '{variable.domain}'"
```

2024-11-21 20:57 UTC, kratman commented on src/pybamm/plotting/quick_plot.py
> +        Dimensional time (in 'time_units') at which to plot. Can be a single time or a list of times.
This needs to be indented to render properly
```suggestion
            Dimensional time (in 'time_units') at which to plot. Can be a single time or a list of times.
```

2024-11-21 20:57 UTC, kratman commented on src/pybamm/plotting/quick_plot.py
> +    def plot(self, t: float | list[float], dynamic: bool = False):
The python 3.9 failure comes from this line, but your change is correct.

Add
```
from __future__ import annotations
```
To the very top of the file

2024-11-21 20:58 UTC, kratman commented on src/pybamm/plotting/quick_plot.py
> +        Dimensional time (in 'time_units') at which to plot. Can be a single time or a list of times.
You can see this if you check the "readthedocs" output in the checks section. It is good to check the docs whenever you update them

2024-11-22 15:17 UTC, agriyakhetarpal submitted a review, later dismissed
Thanks, @medha-14! I only skimmed through the changes and haven't been involved in the review here, I'll request a review from Eric for the final merge.

2024-11-22 15:17 UTC, agriyakhetarpal commented on CHANGELOG.md
> +- Modified `quick_plot.plot` to accept a list of times and generate superimposed graphs for specified time points.([#4529](https://github.com/pybamm-team/PyBaMM/pull/4529))
```suggestion
- Modified `quick_plot.plot` to accept a list of times and generate superimposed graphs for specified time points. ([#4529](https://github.com/pybamm-team/PyBaMM/pull/4529))
```

(nit)

2024-11-22 15:53 UTC, kratman approved these changes
Thanks looks good

2024-11-22 15:55 UTC, kratman commented
@allcontributors add @medha-14 for code

2024-11-22 16:00 UTC, kratman commented
I will merge once I see the windows 3.9 check pass. I do not expect a problem, so this should be merged in a couple minutes

2024-11-22 16:04 UTC, merged

2024-11-22 16:06 UTC, medha-14 commented
Thanks a lot everyone!