Support Python 3.13
pybamm-team/PyBaMM pull request #4552
Opened 2024-10-31 03:21 UTC by elliotwutingfeng

# Description

Update all relevant references to Python version from 3.12 to 3.13, in documentation and CI.

Fixes #4539 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-10-31 09:08 UTC, elliotwutingfeng commented
Looks like the old jaxlib version is incompatible with Python 3.13.

2024-10-31 13:09 UTC, kratman commented
> Looks like the old jaxlib version is incompatible with Python 3.13.

I think newer versions of Jax also drop support for python 3.9, so we might have to drop support of 3.9 in favor of 3.13

2024-10-31 13:12 UTC, kratman requested changes

2024-10-31 18:43 UTC, kratman requested changes
What you need to do next is try to find a Jax version that supports both version 3.9 and version 3.13 for python. It needs to be updated in both utils and the pyproject file.

If you can't find a version that supports both, then we have to do a few other tasks first:
- Remove 3.9
- Remove IREE support (this is planned and is likely needed even if you find a working version of Jax)

I can help you out if needed since this somewhat overlaps with my current tasks

2024-10-31 18:43 UTC, kratman commented on CHANGELOG.md
> +- Added support for Python 3.13 (#4552)
```suggestion
- Added support for Python 3.13 ([#4552)(https://github.com/pybamm-team/PyBaMM/pull/4552)]
```

2024-10-31 18:43 UTC, kratman commented on .github/workflows/run_periodic_tests.yml
> +        if: matrix.os != 'ubuntu-latest' || matrix.python-version != '3.13'
```suggestion
        if: matrix.os != 'ubuntu-latest' || matrix.python-version != '3.12'
```

2024-10-31 18:43 UTC, kratman commented on .github/workflows/run_periodic_tests.yml
> +        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
```suggestion
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
```

2024-10-31 18:43 UTC, kratman commented on .github/workflows/run_periodic_tests.yml
> +        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
```suggestion
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
```

2024-10-31 18:43 UTC, kratman commented on .github/workflows/test_on_push.yml
> +        if: matrix.os != 'ubuntu-latest' || matrix.python-version != '3.13'
```suggestion
        if: matrix.os != 'ubuntu-latest' || matrix.python-version != '3.12'
```

2024-10-31 18:43 UTC, kratman commented on .github/workflows/test_on_push.yml
> +        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
```suggestion
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
```

2024-10-31 18:43 UTC, kratman commented on .github/workflows/test_on_push.yml
> +        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
```suggestion
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
```

2024-11-01 01:32 UTC, elliotwutingfeng commented
I think I'd need help on this one!

2024-11-03 23:20 UTC, agriyakhetarpal commented
> I think I'd need help on this one!

Sure, what can we help you with, @elliotwutingfeng? Based on the suggestions provided above, JAX wheels for Python 3.13 are available post version 0.4.34; you can support multiple versions of JAX using [specifiers](https://packaging.python.org/en/latest/specifications/dependency-specifiers/), i.e., with something like this in the relevant section of the dependencies table:

```toml
# For the Jax solver.
# Note: These must be kept in sync with the versions defined in pybamm/util.py, and
#       must remain compatible with IREE (see noxfile.py for IREE compatibility).
jax = [
    "jax==0.4.27; python_version <"3.13"
    "jaxlib==0.4.34"; python_version <"3.13"
]
```

With this, we don't necessarily need to drop Python 3.9 support right now. However, there's no guarantee that version 0.4.34 will pass the non-IREE (or IREE, even) tests, so you'll need to fix any failing tests if necessary so that both version 0.4.27 and 0.4.34 work (it's unlikely, given how much of JAX's internals we use and the breaking changes there are present between their releases – supporting both is more of a code smell). We can wait on this until we decide on IREE and on updating the JAX version, or if you feel ambitious, please go ahead. cc @jsbrittain has been working on retaining the IREE compiler support with advancing JAX versions just in case he has anything to comment on.

2024-11-08 14:44 UTC, kratman commented on pyproject.toml
> +    "jaxlib==0.4.34; python_version >='3.13'",
Same as above
```suggestion
    "jax==0.4.27; python_version <'3.10'",
    "jaxlib==0.4.27; python_version <'3.10'",
    "jax==0.4.34; python_version >='3.10'",
    "jaxlib==0.4.34; python_version >='3.10'",
```

2024-11-11 16:20 UTC, kratman commented
@elliotwutingfeng Some of your failures can be solved by updating the IREE state function in the nox file:
```python
def set_iree_state():
    """
    Check if IREE is enabled and set the environment variable accordingly.

    Returns
    -------
    str
        "ON" if IREE is enabled, "OFF" otherwise.

    """
    state = "ON" if os.getenv("PYBAMM_IDAKLU_EXPR_IREE", "OFF") == "ON" else "OFF"
    if state == "ON":
        if sys.platform == "win32" or sys.platform == "darwin":
            warnings.warn(
                (
                    "IREE is not enabled on Windows and MacOS. "
                    "Setting PYBAMM_IDAKLU_EXPR_IREE=OFF."
                ),
                stacklevel=2,
            )
            state = "OFF"
        if sys.version_info >= (3, 13):
            warnings.warn(
                (
                    "IREE is not available for Python 3.13 or higher. "
                    "Setting PYBAMM_IDAKLU_EXPR_IREE=OFF."
                ),
                stacklevel=2,
            )
            state = "OFF"
    return state
```

This is part of what I was saying before about this impacting both IREE and 3.9 support. Both of those should be removed in the next year or so.

2024-11-15 01:39 UTC, kratman commented
@elliotwutingfeng Are you still working on this or do you need some help still?

2024-11-15 01:49 UTC, elliotwutingfeng commented
Apologies for the delayed response, I've been caught up with other commitments over the past few days. I think it'll be best for your team to take over this PR. 😅

2024-11-15 01:52 UTC, kratman commented
> Apologies for the delayed response, I've been caught up with other commitments over the past few days. I think it'll be best for your team to take over this PR. 😅

I was not trying to rush you, just asking since we have a release coming out soon. I think you are only 1-2 commits away from being done, but I am more than happy to help you wrap this up

2024-11-15 22:36 UTC, kratman commented
I will try work on that windows failure this weekend. It could be that we just need to update numpy before that works

2024-11-18 02:35 UTC, kratman commented
I tried this out locally on a windows machine with python 3.13, and it looked like it was trying to build some libraries from source for numpy. This was a different failure than the one in the CI (a warning about MinGW built numpy being unstable and likely to crash, right before crashing)

I think this will require updating numpy to get this all working. I am taking a look at that to see how much work would be required

2025-07-02 17:28 UTC, kratman commented
I have my own branch for this now since there were a lot of changes since this was opened. I am going to close this for now

2025-07-02 17:28 UTC, closed without merging