Summary variables calculated only when called
pybamm-team/PyBaMM pull request #4621
Opened 2024-11-26 17:37 UTC by pipliggins

# Description

Fixes #4058 

## Type of change

- [x] Optimization (back-end change that speeds up the code)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-11-28 16:17 UTC, rtimms commented on src/pybamm/solvers/summary_variable.py
> +        # Flag if eSOH calculations are needed
related: https://github.com/pybamm-team/PyBaMM/issues/4619

2024-12-09 16:23 UTC, martinjrobins requested changes
sorry for the delay in the review! This looks great, can you please add to the CHANGELOG under breaking changes, since this changes the api for the summary variables?

2024-12-09 16:23 UTC, martinjrobins commented on src/pybamm/solvers/summary_variable.py
> +        self.cycle_number = np.arange(1, len(self.cycles) + 1)
I can see that at least `cycle_number` is used outside this class, can you please document the attributes that are meant to be public in the docstring?

2024-12-19 16:35 UTC, martinjrobins approved these changes
looks good, thanks @pipliggins

2024-12-19 16:35 UTC, merged