refactor: use pytest fixtures to reduce repetition in tests
pybamm-team/PyBaMM pull request #4723
Opened 2024-12-29 18:52 UTC by Aswinr24

# Description

Refactored the lead-acid model test cases to use pytest fixtures, reducing code duplication and improving test clarity and maintainability.

Related to #4502 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] Code refactor (test improvements to reduce repetition)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

2024-12-30 12:09 UTC, agriyakhetarpal requested changes
I haven't gone through the tests in detail, just skimmed them for now – I think this looks wrong because tests for options such as `{"current collector": "potential pair", "dimensionality": 1}` that were previously present have been removed, apparently. The tests for the lumped thermal model are not present either (and others). Is this ready for review, @Aswinr24, or is this PR in progress and you're writing more tests? Apologies if it's the latter (and please mark it as a draft if it is!)

2024-12-31 18:07 UTC, Aswinr24 commented
Thanks for the feedback @prady0t @agriyakhetarpal ! 
Sure will try adding multiple files in this PR and cover the tests that I believe can be parameterized using fixtures

2025-01-04 09:53 UTC, Aswinr24 commented
@prady0t @agriyakhetarpal Could You Please Review this.
I have tried to cover most of the tests which can be parameterized using fixtures, particularly in case of the Lead Acid Battery Model.
Would like to hear your feedback on this

2025-01-04 22:53 UTC, prady0t commented on tests/integration/test_models/test_full_battery_models/test_lead_acid/test_full.py
Why are the classes removed across all files? My suggestion is to add them back and put all fixtures outside the class (for a better code structure).

2025-01-04 23:09 UTC, prady0t requested changes
Just by looking at the changes, I think we can use [parametrize](https://docs.pytest.org/en/7.1.x/example/parametrize.html) fixture here. @Aswinr24 can you maybe look into ways you can parametrize these tests?
Before that please add the class structure back, it would be easier to review with a cleaner diff.

2025-01-05 11:58 UTC, Aswinr24 commented
@prady0t Thanks for the review, added back the class structure and tried to use the parameterize fixture wherever feasible.
Could you check this now

2025-01-17 15:29 UTC, Aswinr24 commented
@agriyakhetarpal could you please review this submission and check if it is good to go?
Waiting to hear your thoughts on the changes done

2025-01-18 06:09 UTC, agriyakhetarpal commented
Hi @Aswinr24, thanks for your work! I haven't had time to look at these changes in detail, sorry for the delay on this. I'll try to do so this weekend.

2025-02-13 00:15 UTC, Saransh-cpp requested changes
Thanks for picking this up, @Aswinr24! Sorry for the delay in review. See my comments below -

2025-02-13 00:15 UTC, Saransh-cpp commented on tests/integration/test_models/test_full_battery_models/test_lead_acid/test_loqs.py
> +    return pybamm.lead_acid.LOQS()
This looks like a redundant refactor (plus pass-by-sharing might meddle with the tests here), so I would suggest initialising the model in each test (just how it is done right now).

2025-02-13 00:15 UTC, Saransh-cpp commented on tests/integration/test_models/test_full_battery_models/test_lead_acid/test_full.py
> +    def optimisations_test(self):
Can we move this out of the class + rename it to `optimtest` to maintain consistency?

2025-02-13 00:15 UTC, Saransh-cpp commented on tests/integration/test_models/test_full_battery_models/test_lead_acid/test_full.py
> +        "options,t_eval",
```suggestion
        "options, t_eval",
```

2025-02-13 00:16 UTC, Saransh-cpp commented
Could you also resolve the conflicts? Thanks!

2025-02-19 09:47 UTC, Aswinr24 commented
@Saransh-cpp done with my changes needed and resolving conflicts, waiting to hear if it is good to go ?

2025-02-19 10:54 UTC, Saransh-cpp approved these changes
Thanks, @Aswinr24! This looks good to me. I will wait for a review by others before merging this.

2025-02-20 06:31 UTC, prady0t approved these changes
Lgtm. Thanks @Aswinr24!

2025-02-20 17:44 UTC, agriyakhetarpal reviewed
Thanks, @Aswinr24! I have a couple of small suggestions, happy to approve after.

2025-02-20 17:44 UTC, agriyakhetarpal commented on tests/unit/test_models/test_full_battery_models/test_lead_acid/test_full.py
> +            assert isinstance(model.default_solver, expected_solver)
I think this case is a bit different and difficult to follow, as it branches out within a test (for no good reason). Could we move the case where `expected_solver` is `None` back to its own test?

2025-02-20 17:44 UTC, agriyakhetarpal commented on tests/unit/test_models/test_full_battery_models/test_lead_acid/test_loqs.py
> +        ids=["well_posed", "with_convection", "with_convection_1plus1d"],
```suggestion
        ids=["well_posed", "with_convection", "1plus1d"],
```

2025-02-20 17:44 UTC, agriyakhetarpal commented on tests/unit/test_models/test_full_battery_models/test_lead_acid/test_loqs.py
> +        ids=["well_posed", "with_convection", "with_convection_1plus1d"],
Also, the first ID would name the test as `"test_well_posed-well_posed"`, wouldn't it?

2025-02-22 19:13 UTC, Aswinr24 commented on tests/unit/test_models/test_full_battery_models/test_lead_acid/test_loqs.py
> +        ids=["well_posed", "with_convection", "with_convection_1plus1d"],
Yep Changed "well_posed" to "isothermal" to avoid redundancy

2025-02-22 19:17 UTC, Aswinr24 commented
@agriyakhetarpal Done with my changes! waiting to hear if it is good to go ?

2025-02-22 22:03 UTC, merged