Added hypothesis test to two unit testing
pybamm-team/PyBaMM pull request #4724
Opened 2024-12-30 19:19 UTC by RohitP2005

# Description

This change introduces the use of Hypothesis-based testing in two files and is being applied to selective functions as requested by the author and members of the issue https://github.com/pybamm-team/PyBaMM/issues/4703#issuecomment-2564062105

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [x] Optimization (back-end change that speeds up the code)
- [X] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python -m pytest` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python -m pytest --doctest-plus src` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-12-31 12:10 UTC, prady0t commented
@RohitP2005 Add `hypothesis` as a dependency in `pyproject.toml` for checks to pass. 

https://github.com/pybamm-team/PyBaMM/blob/421784e6b0a5f0e857be155b693fec1d9e7ba72d/pyproject.toml#L100

2024-12-31 12:31 UTC, prady0t reviewed
I've added reviews for `test_averages.py`. I'll add reviews for `test_unary_operators.py` once the failing tests are fixed.

2024-12-31 12:31 UTC, prady0t commented on tests/unit/test_expression_tree/test_averages.py
> +        assert average_broad_a == pybamm.Scalar(random_value)
```suggestion
        assert average_broad_a == pybamm.Scalar(random_integer)
```

2024-12-31 12:35 UTC, prady0t commented
Also, fix the PR heading. It's not proper.

2024-12-31 23:16 UTC, RohitP2005 commented on tests/unit/test_expression_tree/test_averages.py
> +    @given(st.integers(min_value=-(2**63), max_value=2**63 - 1))
they are used to made sure that the random values generated are strictly a signed 64-bit integer .

2024-12-31 23:16 UTC, RohitP2005 commented on tests/unit/test_expression_tree/test_averages.py
> +    @given(st.integers(min_value=-(2**63), max_value=2**63 - 1))
explained here at https://github.com/pybamm-team/PyBaMM/pull/4724#discussion_r1900290087

2024-12-31 23:23 UTC, RohitP2005 commented
> I've added reviews for `test_averages.py`. I'll add reviews for `test_unary_operators.py` once the failing tests are fixed.

I've updated the heading as requested, and committed all your suggested changes except for one.
Regarding the implementation of Hypothesis, I limited its use to specific tests to avoid adding overhead by applying it to too many cases. Do you think the way I implemented Hypothesis is optimized, or are there areas where I can improve further?

2025-01-07 18:53 UTC, prady0t requested changes

2025-01-07 18:53 UTC, prady0t commented on tests/unit/test_expression_tree/test_unary_operators.py
> +    @given(random_value=st.floats(min_value=-1e3, max_value=1e3))
```suggestion
    @given(st.floats(min_value=-1e38, max_value=0))
```
Since we are only working with negative numbers.

2025-01-07 18:53 UTC, prady0t commented on tests/unit/test_expression_tree/test_unary_operators.py
> +        b = pybamm.Scalar(-random_value)
```suggestion
        b = pybamm.Scalar(random_value)
```

2025-01-07 18:53 UTC, prady0t commented on tests/unit/test_expression_tree/test_unary_operators.py
> +        assert absb.evaluate() == abs(random_value)
```suggestion
        assert absb.evaluate() == -random_value
```

2025-01-07 18:53 UTC, prady0t commented on tests/unit/test_expression_tree/test_unary_operators.py
> +    )
```suggestion
        random_value1=st.floats(min_value=-1e38, max_value=1e38),
        random_value2=st.floats(min_value=-1e38, max_value=1e38),
    )
```
If there's a particular reason you are keeping for small range here and everywhere else, I'll be glad to know.

2025-01-07 18:53 UTC, prady0t commented on tests/unit/test_expression_tree/test_unary_operators.py
> +        random_value2=st.floats(min_value=-1e3, max_value=1e3),
```suggestion
    @given(
        random_value1=st.floats(min_value=-1e38, max_value=1e38),
        random_value2=st.floats(min_value=-1e38, max_value=1e38),
```

2025-01-07 18:53 UTC, prady0t commented on tests/unit/test_expression_tree/test_unary_operators.py
> +        ),
Can we increase the size here? i'll look into this bit later

2025-01-07 18:53 UTC, prady0t commented on tests/unit/test_expression_tree/test_unary_operators.py
> +    @given(random_value=st.floats(min_value=-1e3, max_value=1e3))
```suggestion
    @given(random_value=st.floats(min_value=-1e38, max_value=1e38))
```

2025-01-08 01:24 UTC, RohitP2005 commented on tests/unit/test_expression_tree/test_unary_operators.py
> +        ),
okay , i guess 10 will be good number

2025-01-10 22:55 UTC, kratman commented
@RohitP2005 you keep merging develop into this branch, but there are still a bunch of failing tests. Can you fix those so the review can continue

2025-01-11 03:23 UTC, RohitP2005 commented
> @RohitP2005 you keep merging develop into this branch, but there are still a bunch of failing tests. Can you fix those so the review can continue

Sorry about that, my previous commit passed the CI test, after the new branch merge it is failing.

I will look into it asap.

2025-02-02 17:31 UTC, RohitP2005 commented on tests/unit/test_expression_tree/test_unary_operators.py
> +        ),
hey @prady0t shall i go with ```min_size=10``` also i thought of creating a new PR by closing this one, cause it sflooded with too much of commits

2025-02-02 19:42 UTC, agriyakhetarpal commented on tests/unit/test_expression_tree/test_unary_operators.py
> +        ),
I think this PR is fine; it preserves the review comments in one place. Once the PR and the reviews are completed, please feel free to squash unnecessary commits as an exercise, or we can do it as we squash-merge PRs anyway.

2025-02-10 16:38 UTC, RohitP2005 commented
Hey @agriyakhetarpal  can u trigger the CI workflows for this branch

2025-02-10 16:45 UTC, kratman commented
@RohitP2005 Triggered CI and updated the branch

2025-02-13 00:28 UTC, Saransh-cpp commented
Requesting a review from @prady0t on this.

2025-02-13 08:44 UTC, RohitP2005 commented
> @RohitP2005 Triggered CI and updated the branch

thanks @kratman 
i will look into the failing docs build asap

2025-02-22 16:34 UTC, RohitP2005 commented
Hey @agriyakhetarpal  I need updates on this PR. Its been there for a long time.
Looking forward to complete this and move on to the next one.

2025-02-22 17:44 UTC, agriyakhetarpal reviewed
Done. Sorry for the delay in the review, @RohitP2005! Thanks for your work here. I just have one comment – happy to approve after that.

2025-02-22 17:44 UTC, agriyakhetarpal commented on pyproject.toml
> +    "hypothesis",
Could you please move this to the "dev" extras below in the file?

2025-02-22 18:12 UTC, RohitP2005 commented on pyproject.toml
> +    "hypothesis",
@agriyakhetarpal Took care of that also with the latest commit

2025-02-22 18:13 UTC, agriyakhetarpal approved these changes

2025-02-22 18:15 UTC, agriyakhetarpal commented
Hi @prady0t, I plan to merge this early next week so that @RohitP2005 can proceed further – unless you have comments by then.

2025-02-22 18:16 UTC, RohitP2005 commented
@agriyakhetarpal I would like a final check by @prady0t 
before merging this.
Cause there's lot other tests that need property based testing.
It would helpful if you suggest what to do next on this matter.

2025-02-22 18:50 UTC, kratman commented
> Cause there's lot other tests that need property based testing. It would helpful if you suggest what to do next on this matter.

I think I would like to see this be limited to only where it is needed and useful rather than all tests. We would not want to cause the complexity and runtime of our tests to explode from excessive testing. The functions you have done so far are fairly straight forward, but tests in other parts of the code can be quite slow and complicated.

My other concern is that the codebase is physics based, so you need to make sure that the value ranges make sense for the codebase as well. Some parameters may only be valid in the 0-1 range or need to be only positive floats.

2025-02-24 19:28 UTC, prady0t commented on tests/unit/test_expression_tree/test_averages.py
> +    @given(st.integers(min_value=-(2**63), max_value=2**63 - 1))
@kratman Here's an example of how hypothesis could be helpful. Any value out of this range throws an error. Even though this is a very large value and does not make any sense, we may have such discrepancies with other functions.

2025-02-24 19:35 UTC, prady0t commented
Other than the above review, everything look good. Thanks @RohitP2005

2025-02-24 21:10 UTC, merged